// Code generated by go-swagger; DO NOT EDIT.

package f_y_i

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteFyiDeliveryoptionsDeviceIDParams creates a new DeleteFyiDeliveryoptionsDeviceIDParams object
// with the default values initialized.
func NewDeleteFyiDeliveryoptionsDeviceIDParams() *DeleteFyiDeliveryoptionsDeviceIDParams {
	var ()
	return &DeleteFyiDeliveryoptionsDeviceIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteFyiDeliveryoptionsDeviceIDParamsWithTimeout creates a new DeleteFyiDeliveryoptionsDeviceIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteFyiDeliveryoptionsDeviceIDParamsWithTimeout(timeout time.Duration) *DeleteFyiDeliveryoptionsDeviceIDParams {
	var ()
	return &DeleteFyiDeliveryoptionsDeviceIDParams{

		timeout: timeout,
	}
}

// NewDeleteFyiDeliveryoptionsDeviceIDParamsWithContext creates a new DeleteFyiDeliveryoptionsDeviceIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteFyiDeliveryoptionsDeviceIDParamsWithContext(ctx context.Context) *DeleteFyiDeliveryoptionsDeviceIDParams {
	var ()
	return &DeleteFyiDeliveryoptionsDeviceIDParams{

		Context: ctx,
	}
}

// NewDeleteFyiDeliveryoptionsDeviceIDParamsWithHTTPClient creates a new DeleteFyiDeliveryoptionsDeviceIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteFyiDeliveryoptionsDeviceIDParamsWithHTTPClient(client *http.Client) *DeleteFyiDeliveryoptionsDeviceIDParams {
	var ()
	return &DeleteFyiDeliveryoptionsDeviceIDParams{
		HTTPClient: client,
	}
}

/*DeleteFyiDeliveryoptionsDeviceIDParams contains all the parameters to send to the API endpoint
for the delete fyi deliveryoptions device ID operation typically these are written to a http.Request
*/
type DeleteFyiDeliveryoptionsDeviceIDParams struct {

	/*DeviceID
	  device ID

	*/
	DeviceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete fyi deliveryoptions device ID params
func (o *DeleteFyiDeliveryoptionsDeviceIDParams) WithTimeout(timeout time.Duration) *DeleteFyiDeliveryoptionsDeviceIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete fyi deliveryoptions device ID params
func (o *DeleteFyiDeliveryoptionsDeviceIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete fyi deliveryoptions device ID params
func (o *DeleteFyiDeliveryoptionsDeviceIDParams) WithContext(ctx context.Context) *DeleteFyiDeliveryoptionsDeviceIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete fyi deliveryoptions device ID params
func (o *DeleteFyiDeliveryoptionsDeviceIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete fyi deliveryoptions device ID params
func (o *DeleteFyiDeliveryoptionsDeviceIDParams) WithHTTPClient(client *http.Client) *DeleteFyiDeliveryoptionsDeviceIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete fyi deliveryoptions device ID params
func (o *DeleteFyiDeliveryoptionsDeviceIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceID adds the deviceID to the delete fyi deliveryoptions device ID params
func (o *DeleteFyiDeliveryoptionsDeviceIDParams) WithDeviceID(deviceID string) *DeleteFyiDeliveryoptionsDeviceIDParams {
	o.SetDeviceID(deviceID)
	return o
}

// SetDeviceID adds the deviceId to the delete fyi deliveryoptions device ID params
func (o *DeleteFyiDeliveryoptionsDeviceIDParams) SetDeviceID(deviceID string) {
	o.DeviceID = deviceID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteFyiDeliveryoptionsDeviceIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param deviceId
	if err := r.SetPathParam("deviceId", o.DeviceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
