// Code generated by go-swagger; DO NOT EDIT.

package f_y_i

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFyiUnreadnumberParams creates a new GetFyiUnreadnumberParams object
// with the default values initialized.
func NewGetFyiUnreadnumberParams() *GetFyiUnreadnumberParams {

	return &GetFyiUnreadnumberParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFyiUnreadnumberParamsWithTimeout creates a new GetFyiUnreadnumberParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFyiUnreadnumberParamsWithTimeout(timeout time.Duration) *GetFyiUnreadnumberParams {

	return &GetFyiUnreadnumberParams{

		timeout: timeout,
	}
}

// NewGetFyiUnreadnumberParamsWithContext creates a new GetFyiUnreadnumberParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFyiUnreadnumberParamsWithContext(ctx context.Context) *GetFyiUnreadnumberParams {

	return &GetFyiUnreadnumberParams{

		Context: ctx,
	}
}

// NewGetFyiUnreadnumberParamsWithHTTPClient creates a new GetFyiUnreadnumberParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFyiUnreadnumberParamsWithHTTPClient(client *http.Client) *GetFyiUnreadnumberParams {

	return &GetFyiUnreadnumberParams{
		HTTPClient: client,
	}
}

/*GetFyiUnreadnumberParams contains all the parameters to send to the API endpoint
for the get fyi unreadnumber operation typically these are written to a http.Request
*/
type GetFyiUnreadnumberParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get fyi unreadnumber params
func (o *GetFyiUnreadnumberParams) WithTimeout(timeout time.Duration) *GetFyiUnreadnumberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fyi unreadnumber params
func (o *GetFyiUnreadnumberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fyi unreadnumber params
func (o *GetFyiUnreadnumberParams) WithContext(ctx context.Context) *GetFyiUnreadnumberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fyi unreadnumber params
func (o *GetFyiUnreadnumberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fyi unreadnumber params
func (o *GetFyiUnreadnumberParams) WithHTTPClient(client *http.Client) *GetFyiUnreadnumberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fyi unreadnumber params
func (o *GetFyiUnreadnumberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetFyiUnreadnumberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
