// Code generated by go-swagger; DO NOT EDIT.

package f_y_i

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFyiNotificationsMoreParams creates a new GetFyiNotificationsMoreParams object
// with the default values initialized.
func NewGetFyiNotificationsMoreParams() *GetFyiNotificationsMoreParams {
	var ()
	return &GetFyiNotificationsMoreParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFyiNotificationsMoreParamsWithTimeout creates a new GetFyiNotificationsMoreParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFyiNotificationsMoreParamsWithTimeout(timeout time.Duration) *GetFyiNotificationsMoreParams {
	var ()
	return &GetFyiNotificationsMoreParams{

		timeout: timeout,
	}
}

// NewGetFyiNotificationsMoreParamsWithContext creates a new GetFyiNotificationsMoreParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFyiNotificationsMoreParamsWithContext(ctx context.Context) *GetFyiNotificationsMoreParams {
	var ()
	return &GetFyiNotificationsMoreParams{

		Context: ctx,
	}
}

// NewGetFyiNotificationsMoreParamsWithHTTPClient creates a new GetFyiNotificationsMoreParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFyiNotificationsMoreParamsWithHTTPClient(client *http.Client) *GetFyiNotificationsMoreParams {
	var ()
	return &GetFyiNotificationsMoreParams{
		HTTPClient: client,
	}
}

/*GetFyiNotificationsMoreParams contains all the parameters to send to the API endpoint
for the get fyi notifications more operation typically these are written to a http.Request
*/
type GetFyiNotificationsMoreParams struct {

	/*ID
	  id of last notification in the list

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get fyi notifications more params
func (o *GetFyiNotificationsMoreParams) WithTimeout(timeout time.Duration) *GetFyiNotificationsMoreParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fyi notifications more params
func (o *GetFyiNotificationsMoreParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fyi notifications more params
func (o *GetFyiNotificationsMoreParams) WithContext(ctx context.Context) *GetFyiNotificationsMoreParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fyi notifications more params
func (o *GetFyiNotificationsMoreParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fyi notifications more params
func (o *GetFyiNotificationsMoreParams) WithHTTPClient(client *http.Client) *GetFyiNotificationsMoreParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fyi notifications more params
func (o *GetFyiNotificationsMoreParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get fyi notifications more params
func (o *GetFyiNotificationsMoreParams) WithID(id string) *GetFyiNotificationsMoreParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get fyi notifications more params
func (o *GetFyiNotificationsMoreParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetFyiNotificationsMoreParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := qrID
	if qID != "" {
		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
