// Code generated by go-swagger; DO NOT EDIT.

package f_y_i

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// PostFyiDeliveryoptionsDeviceReader is a Reader for the PostFyiDeliveryoptionsDevice structure.
type PostFyiDeliveryoptionsDeviceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostFyiDeliveryoptionsDeviceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostFyiDeliveryoptionsDeviceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostFyiDeliveryoptionsDeviceOK creates a PostFyiDeliveryoptionsDeviceOK with default headers values
func NewPostFyiDeliveryoptionsDeviceOK() *PostFyiDeliveryoptionsDeviceOK {
	return &PostFyiDeliveryoptionsDeviceOK{}
}

/*PostFyiDeliveryoptionsDeviceOK handles this case with default header values.

200 means successful
*/
type PostFyiDeliveryoptionsDeviceOK struct {
	Payload *PostFyiDeliveryoptionsDeviceOKBody
}

func (o *PostFyiDeliveryoptionsDeviceOK) Error() string {
	return fmt.Sprintf("[POST /fyi/deliveryoptions/device][%d] postFyiDeliveryoptionsDeviceOK  %+v", 200, o.Payload)
}

func (o *PostFyiDeliveryoptionsDeviceOK) GetPayload() *PostFyiDeliveryoptionsDeviceOKBody {
	return o.Payload
}

func (o *PostFyiDeliveryoptionsDeviceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostFyiDeliveryoptionsDeviceOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostFyiDeliveryoptionsDeviceBody post fyi deliveryoptions device body
swagger:model PostFyiDeliveryoptionsDeviceBody
*/
type PostFyiDeliveryoptionsDeviceBody struct {

	// device Id
	DeviceID string `json:"deviceId,omitempty"`

	// devicename
	Devicename string `json:"devicename,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// ui name
	UIName string `json:"uiName,omitempty"`
}

// Validate validates this post fyi deliveryoptions device body
func (o *PostFyiDeliveryoptionsDeviceBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostFyiDeliveryoptionsDeviceBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostFyiDeliveryoptionsDeviceBody) UnmarshalBinary(b []byte) error {
	var res PostFyiDeliveryoptionsDeviceBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostFyiDeliveryoptionsDeviceOKBody post fyi deliveryoptions device o k body
swagger:model PostFyiDeliveryoptionsDeviceOKBody
*/
type PostFyiDeliveryoptionsDeviceOKBody struct {

	// t
	T int64 `json:"T,omitempty"`

	// v
	V int64 `json:"V,omitempty"`
}

// Validate validates this post fyi deliveryoptions device o k body
func (o *PostFyiDeliveryoptionsDeviceOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostFyiDeliveryoptionsDeviceOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostFyiDeliveryoptionsDeviceOKBody) UnmarshalBinary(b []byte) error {
	var res PostFyiDeliveryoptionsDeviceOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
