// Code generated by go-swagger; DO NOT EDIT.

package f_y_i

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostFyiDeliveryoptionsDeviceParams creates a new PostFyiDeliveryoptionsDeviceParams object
// with the default values initialized.
func NewPostFyiDeliveryoptionsDeviceParams() *PostFyiDeliveryoptionsDeviceParams {
	var ()
	return &PostFyiDeliveryoptionsDeviceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostFyiDeliveryoptionsDeviceParamsWithTimeout creates a new PostFyiDeliveryoptionsDeviceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostFyiDeliveryoptionsDeviceParamsWithTimeout(timeout time.Duration) *PostFyiDeliveryoptionsDeviceParams {
	var ()
	return &PostFyiDeliveryoptionsDeviceParams{

		timeout: timeout,
	}
}

// NewPostFyiDeliveryoptionsDeviceParamsWithContext creates a new PostFyiDeliveryoptionsDeviceParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostFyiDeliveryoptionsDeviceParamsWithContext(ctx context.Context) *PostFyiDeliveryoptionsDeviceParams {
	var ()
	return &PostFyiDeliveryoptionsDeviceParams{

		Context: ctx,
	}
}

// NewPostFyiDeliveryoptionsDeviceParamsWithHTTPClient creates a new PostFyiDeliveryoptionsDeviceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostFyiDeliveryoptionsDeviceParamsWithHTTPClient(client *http.Client) *PostFyiDeliveryoptionsDeviceParams {
	var ()
	return &PostFyiDeliveryoptionsDeviceParams{
		HTTPClient: client,
	}
}

/*PostFyiDeliveryoptionsDeviceParams contains all the parameters to send to the API endpoint
for the post fyi deliveryoptions device operation typically these are written to a http.Request
*/
type PostFyiDeliveryoptionsDeviceParams struct {

	/*Body
	  device info

	*/
	Body PostFyiDeliveryoptionsDeviceBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post fyi deliveryoptions device params
func (o *PostFyiDeliveryoptionsDeviceParams) WithTimeout(timeout time.Duration) *PostFyiDeliveryoptionsDeviceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post fyi deliveryoptions device params
func (o *PostFyiDeliveryoptionsDeviceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post fyi deliveryoptions device params
func (o *PostFyiDeliveryoptionsDeviceParams) WithContext(ctx context.Context) *PostFyiDeliveryoptionsDeviceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post fyi deliveryoptions device params
func (o *PostFyiDeliveryoptionsDeviceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post fyi deliveryoptions device params
func (o *PostFyiDeliveryoptionsDeviceParams) WithHTTPClient(client *http.Client) *PostFyiDeliveryoptionsDeviceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post fyi deliveryoptions device params
func (o *PostFyiDeliveryoptionsDeviceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post fyi deliveryoptions device params
func (o *PostFyiDeliveryoptionsDeviceParams) WithBody(body PostFyiDeliveryoptionsDeviceBody) *PostFyiDeliveryoptionsDeviceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post fyi deliveryoptions device params
func (o *PostFyiDeliveryoptionsDeviceParams) SetBody(body PostFyiDeliveryoptionsDeviceBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostFyiDeliveryoptionsDeviceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
