// Code generated by go-swagger; DO NOT EDIT.

package f_y_i

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostFyiSettingsTypecodeParams creates a new PostFyiSettingsTypecodeParams object
// with the default values initialized.
func NewPostFyiSettingsTypecodeParams() *PostFyiSettingsTypecodeParams {
	var ()
	return &PostFyiSettingsTypecodeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostFyiSettingsTypecodeParamsWithTimeout creates a new PostFyiSettingsTypecodeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostFyiSettingsTypecodeParamsWithTimeout(timeout time.Duration) *PostFyiSettingsTypecodeParams {
	var ()
	return &PostFyiSettingsTypecodeParams{

		timeout: timeout,
	}
}

// NewPostFyiSettingsTypecodeParamsWithContext creates a new PostFyiSettingsTypecodeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostFyiSettingsTypecodeParamsWithContext(ctx context.Context) *PostFyiSettingsTypecodeParams {
	var ()
	return &PostFyiSettingsTypecodeParams{

		Context: ctx,
	}
}

// NewPostFyiSettingsTypecodeParamsWithHTTPClient creates a new PostFyiSettingsTypecodeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostFyiSettingsTypecodeParamsWithHTTPClient(client *http.Client) *PostFyiSettingsTypecodeParams {
	var ()
	return &PostFyiSettingsTypecodeParams{
		HTTPClient: client,
	}
}

/*PostFyiSettingsTypecodeParams contains all the parameters to send to the API endpoint
for the post fyi settings typecode operation typically these are written to a http.Request
*/
type PostFyiSettingsTypecodeParams struct {

	/*Body*/
	Body PostFyiSettingsTypecodeBody
	/*Typecode
	  fyi code

	*/
	Typecode string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post fyi settings typecode params
func (o *PostFyiSettingsTypecodeParams) WithTimeout(timeout time.Duration) *PostFyiSettingsTypecodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post fyi settings typecode params
func (o *PostFyiSettingsTypecodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post fyi settings typecode params
func (o *PostFyiSettingsTypecodeParams) WithContext(ctx context.Context) *PostFyiSettingsTypecodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post fyi settings typecode params
func (o *PostFyiSettingsTypecodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post fyi settings typecode params
func (o *PostFyiSettingsTypecodeParams) WithHTTPClient(client *http.Client) *PostFyiSettingsTypecodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post fyi settings typecode params
func (o *PostFyiSettingsTypecodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post fyi settings typecode params
func (o *PostFyiSettingsTypecodeParams) WithBody(body PostFyiSettingsTypecodeBody) *PostFyiSettingsTypecodeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post fyi settings typecode params
func (o *PostFyiSettingsTypecodeParams) SetBody(body PostFyiSettingsTypecodeBody) {
	o.Body = body
}

// WithTypecode adds the typecode to the post fyi settings typecode params
func (o *PostFyiSettingsTypecodeParams) WithTypecode(typecode string) *PostFyiSettingsTypecodeParams {
	o.SetTypecode(typecode)
	return o
}

// SetTypecode adds the typecode to the post fyi settings typecode params
func (o *PostFyiSettingsTypecodeParams) SetTypecode(typecode string) {
	o.Typecode = typecode
}

// WriteToRequest writes these params to a swagger request
func (o *PostFyiSettingsTypecodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param typecode
	if err := r.SetPathParam("typecode", o.Typecode); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
