// Code generated by go-swagger; DO NOT EDIT.

package f_y_i

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// PutFyiDeliveryoptionsEmailReader is a Reader for the PutFyiDeliveryoptionsEmail structure.
type PutFyiDeliveryoptionsEmailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutFyiDeliveryoptionsEmailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutFyiDeliveryoptionsEmailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutFyiDeliveryoptionsEmailOK creates a PutFyiDeliveryoptionsEmailOK with default headers values
func NewPutFyiDeliveryoptionsEmailOK() *PutFyiDeliveryoptionsEmailOK {
	return &PutFyiDeliveryoptionsEmailOK{}
}

/*PutFyiDeliveryoptionsEmailOK handles this case with default header values.

200 means successful
*/
type PutFyiDeliveryoptionsEmailOK struct {
	Payload *PutFyiDeliveryoptionsEmailOKBody
}

func (o *PutFyiDeliveryoptionsEmailOK) Error() string {
	return fmt.Sprintf("[PUT /fyi/deliveryoptions/email][%d] putFyiDeliveryoptionsEmailOK  %+v", 200, o.Payload)
}

func (o *PutFyiDeliveryoptionsEmailOK) GetPayload() *PutFyiDeliveryoptionsEmailOKBody {
	return o.Payload
}

func (o *PutFyiDeliveryoptionsEmailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PutFyiDeliveryoptionsEmailOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PutFyiDeliveryoptionsEmailOKBody put fyi deliveryoptions email o k body
swagger:model PutFyiDeliveryoptionsEmailOKBody
*/
type PutFyiDeliveryoptionsEmailOKBody struct {

	// t
	T int64 `json:"T,omitempty"`

	// v
	V int64 `json:"V,omitempty"`
}

// Validate validates this put fyi deliveryoptions email o k body
func (o *PutFyiDeliveryoptionsEmailOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutFyiDeliveryoptionsEmailOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutFyiDeliveryoptionsEmailOKBody) UnmarshalBinary(b []byte) error {
	var res PutFyiDeliveryoptionsEmailOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
