// Code generated by go-swagger; DO NOT EDIT.

package f_y_i

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutFyiNotificationsNotificationIDReader is a Reader for the PutFyiNotificationsNotificationID structure.
type PutFyiNotificationsNotificationIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutFyiNotificationsNotificationIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutFyiNotificationsNotificationIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutFyiNotificationsNotificationIDOK creates a PutFyiNotificationsNotificationIDOK with default headers values
func NewPutFyiNotificationsNotificationIDOK() *PutFyiNotificationsNotificationIDOK {
	return &PutFyiNotificationsNotificationIDOK{}
}

/*PutFyiNotificationsNotificationIDOK handles this case with default header values.

when 200 receives, it means successful
*/
type PutFyiNotificationsNotificationIDOK struct {
	Payload interface{}
}

func (o *PutFyiNotificationsNotificationIDOK) Error() string {
	return fmt.Sprintf("[PUT /fyi/notifications/{notificationId}][%d] putFyiNotificationsNotificationIdOK  %+v", 200, o.Payload)
}

func (o *PutFyiNotificationsNotificationIDOK) GetPayload() interface{} {
	return o.Payload
}

func (o *PutFyiNotificationsNotificationIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
