// Code generated by go-swagger; DO NOT EDIT.

package f_y_i

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutFyiDeliveryoptionsEmailParams creates a new PutFyiDeliveryoptionsEmailParams object
// with the default values initialized.
func NewPutFyiDeliveryoptionsEmailParams() *PutFyiDeliveryoptionsEmailParams {
	var ()
	return &PutFyiDeliveryoptionsEmailParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutFyiDeliveryoptionsEmailParamsWithTimeout creates a new PutFyiDeliveryoptionsEmailParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutFyiDeliveryoptionsEmailParamsWithTimeout(timeout time.Duration) *PutFyiDeliveryoptionsEmailParams {
	var ()
	return &PutFyiDeliveryoptionsEmailParams{

		timeout: timeout,
	}
}

// NewPutFyiDeliveryoptionsEmailParamsWithContext creates a new PutFyiDeliveryoptionsEmailParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutFyiDeliveryoptionsEmailParamsWithContext(ctx context.Context) *PutFyiDeliveryoptionsEmailParams {
	var ()
	return &PutFyiDeliveryoptionsEmailParams{

		Context: ctx,
	}
}

// NewPutFyiDeliveryoptionsEmailParamsWithHTTPClient creates a new PutFyiDeliveryoptionsEmailParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutFyiDeliveryoptionsEmailParamsWithHTTPClient(client *http.Client) *PutFyiDeliveryoptionsEmailParams {
	var ()
	return &PutFyiDeliveryoptionsEmailParams{
		HTTPClient: client,
	}
}

/*PutFyiDeliveryoptionsEmailParams contains all the parameters to send to the API endpoint
for the put fyi deliveryoptions email operation typically these are written to a http.Request
*/
type PutFyiDeliveryoptionsEmailParams struct {

	/*Enabled
	  true/false

	*/
	Enabled string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put fyi deliveryoptions email params
func (o *PutFyiDeliveryoptionsEmailParams) WithTimeout(timeout time.Duration) *PutFyiDeliveryoptionsEmailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put fyi deliveryoptions email params
func (o *PutFyiDeliveryoptionsEmailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put fyi deliveryoptions email params
func (o *PutFyiDeliveryoptionsEmailParams) WithContext(ctx context.Context) *PutFyiDeliveryoptionsEmailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put fyi deliveryoptions email params
func (o *PutFyiDeliveryoptionsEmailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put fyi deliveryoptions email params
func (o *PutFyiDeliveryoptionsEmailParams) WithHTTPClient(client *http.Client) *PutFyiDeliveryoptionsEmailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put fyi deliveryoptions email params
func (o *PutFyiDeliveryoptionsEmailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnabled adds the enabled to the put fyi deliveryoptions email params
func (o *PutFyiDeliveryoptionsEmailParams) WithEnabled(enabled string) *PutFyiDeliveryoptionsEmailParams {
	o.SetEnabled(enabled)
	return o
}

// SetEnabled adds the enabled to the put fyi deliveryoptions email params
func (o *PutFyiDeliveryoptionsEmailParams) SetEnabled(enabled string) {
	o.Enabled = enabled
}

// WriteToRequest writes these params to a swagger request
func (o *PutFyiDeliveryoptionsEmailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param enabled
	qrEnabled := o.Enabled
	qEnabled := qrEnabled
	if qEnabled != "" {
		if err := r.SetQueryParam("enabled", qEnabled); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
