// Code generated by go-swagger; DO NOT EDIT.

package f_y_i

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutFyiNotificationsNotificationIDParams creates a new PutFyiNotificationsNotificationIDParams object
// with the default values initialized.
func NewPutFyiNotificationsNotificationIDParams() *PutFyiNotificationsNotificationIDParams {
	var ()
	return &PutFyiNotificationsNotificationIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutFyiNotificationsNotificationIDParamsWithTimeout creates a new PutFyiNotificationsNotificationIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutFyiNotificationsNotificationIDParamsWithTimeout(timeout time.Duration) *PutFyiNotificationsNotificationIDParams {
	var ()
	return &PutFyiNotificationsNotificationIDParams{

		timeout: timeout,
	}
}

// NewPutFyiNotificationsNotificationIDParamsWithContext creates a new PutFyiNotificationsNotificationIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutFyiNotificationsNotificationIDParamsWithContext(ctx context.Context) *PutFyiNotificationsNotificationIDParams {
	var ()
	return &PutFyiNotificationsNotificationIDParams{

		Context: ctx,
	}
}

// NewPutFyiNotificationsNotificationIDParamsWithHTTPClient creates a new PutFyiNotificationsNotificationIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutFyiNotificationsNotificationIDParamsWithHTTPClient(client *http.Client) *PutFyiNotificationsNotificationIDParams {
	var ()
	return &PutFyiNotificationsNotificationIDParams{
		HTTPClient: client,
	}
}

/*PutFyiNotificationsNotificationIDParams contains all the parameters to send to the API endpoint
for the put fyi notifications notification ID operation typically these are written to a http.Request
*/
type PutFyiNotificationsNotificationIDParams struct {

	/*NotificationID
	  mark a notification read

	*/
	NotificationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put fyi notifications notification ID params
func (o *PutFyiNotificationsNotificationIDParams) WithTimeout(timeout time.Duration) *PutFyiNotificationsNotificationIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put fyi notifications notification ID params
func (o *PutFyiNotificationsNotificationIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put fyi notifications notification ID params
func (o *PutFyiNotificationsNotificationIDParams) WithContext(ctx context.Context) *PutFyiNotificationsNotificationIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put fyi notifications notification ID params
func (o *PutFyiNotificationsNotificationIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put fyi notifications notification ID params
func (o *PutFyiNotificationsNotificationIDParams) WithHTTPClient(client *http.Client) *PutFyiNotificationsNotificationIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put fyi notifications notification ID params
func (o *PutFyiNotificationsNotificationIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNotificationID adds the notificationID to the put fyi notifications notification ID params
func (o *PutFyiNotificationsNotificationIDParams) WithNotificationID(notificationID string) *PutFyiNotificationsNotificationIDParams {
	o.SetNotificationID(notificationID)
	return o
}

// SetNotificationID adds the notificationId to the put fyi notifications notification ID params
func (o *PutFyiNotificationsNotificationIDParams) SetNotificationID(notificationID string) {
	o.NotificationID = notificationID
}

// WriteToRequest writes these params to a swagger request
func (o *PutFyiNotificationsNotificationIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param notificationId
	if err := r.SetPathParam("notificationId", o.NotificationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
