// Code generated by go-swagger; DO NOT EDIT.

package f_y_i

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutFyiDisclaimerTypecodeParams creates a new PutFyiDisclaimerTypecodeParams object
// with the default values initialized.
func NewPutFyiDisclaimerTypecodeParams() *PutFyiDisclaimerTypecodeParams {
	var ()
	return &PutFyiDisclaimerTypecodeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutFyiDisclaimerTypecodeParamsWithTimeout creates a new PutFyiDisclaimerTypecodeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutFyiDisclaimerTypecodeParamsWithTimeout(timeout time.Duration) *PutFyiDisclaimerTypecodeParams {
	var ()
	return &PutFyiDisclaimerTypecodeParams{

		timeout: timeout,
	}
}

// NewPutFyiDisclaimerTypecodeParamsWithContext creates a new PutFyiDisclaimerTypecodeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutFyiDisclaimerTypecodeParamsWithContext(ctx context.Context) *PutFyiDisclaimerTypecodeParams {
	var ()
	return &PutFyiDisclaimerTypecodeParams{

		Context: ctx,
	}
}

// NewPutFyiDisclaimerTypecodeParamsWithHTTPClient creates a new PutFyiDisclaimerTypecodeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutFyiDisclaimerTypecodeParamsWithHTTPClient(client *http.Client) *PutFyiDisclaimerTypecodeParams {
	var ()
	return &PutFyiDisclaimerTypecodeParams{
		HTTPClient: client,
	}
}

/*PutFyiDisclaimerTypecodeParams contains all the parameters to send to the API endpoint
for the put fyi disclaimer typecode operation typically these are written to a http.Request
*/
type PutFyiDisclaimerTypecodeParams struct {

	/*Typecode
	  fyi code, for example --M8, EA

	*/
	Typecode string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put fyi disclaimer typecode params
func (o *PutFyiDisclaimerTypecodeParams) WithTimeout(timeout time.Duration) *PutFyiDisclaimerTypecodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put fyi disclaimer typecode params
func (o *PutFyiDisclaimerTypecodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put fyi disclaimer typecode params
func (o *PutFyiDisclaimerTypecodeParams) WithContext(ctx context.Context) *PutFyiDisclaimerTypecodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put fyi disclaimer typecode params
func (o *PutFyiDisclaimerTypecodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put fyi disclaimer typecode params
func (o *PutFyiDisclaimerTypecodeParams) WithHTTPClient(client *http.Client) *PutFyiDisclaimerTypecodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put fyi disclaimer typecode params
func (o *PutFyiDisclaimerTypecodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTypecode adds the typecode to the put fyi disclaimer typecode params
func (o *PutFyiDisclaimerTypecodeParams) WithTypecode(typecode string) *PutFyiDisclaimerTypecodeParams {
	o.SetTypecode(typecode)
	return o
}

// SetTypecode adds the typecode to the put fyi disclaimer typecode params
func (o *PutFyiDisclaimerTypecodeParams) SetTypecode(typecode string) {
	o.Typecode = typecode
}

// WriteToRequest writes these params to a swagger request
func (o *PutFyiDisclaimerTypecodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param typecode
	if err := r.SetPathParam("typecode", o.Typecode); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
