// Code generated by go-swagger; DO NOT EDIT.

package portfolio

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostPortfolioAccountIDPositionsInvalidateReader is a Reader for the PostPortfolioAccountIDPositionsInvalidate structure.
type PostPortfolioAccountIDPositionsInvalidateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostPortfolioAccountIDPositionsInvalidateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostPortfolioAccountIDPositionsInvalidateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostPortfolioAccountIDPositionsInvalidateOK creates a PostPortfolioAccountIDPositionsInvalidateOK with default headers values
func NewPostPortfolioAccountIDPositionsInvalidateOK() *PostPortfolioAccountIDPositionsInvalidateOK {
	return &PostPortfolioAccountIDPositionsInvalidateOK{}
}

/*PostPortfolioAccountIDPositionsInvalidateOK handles this case with default header values.

200 means successful
*/
type PostPortfolioAccountIDPositionsInvalidateOK struct {
	Payload interface{}
}

func (o *PostPortfolioAccountIDPositionsInvalidateOK) Error() string {
	return fmt.Sprintf("[POST /portfolio/{accountId}/positions/invalidate][%d] postPortfolioAccountIdPositionsInvalidateOK  %+v", 200, o.Payload)
}

func (o *PostPortfolioAccountIDPositionsInvalidateOK) GetPayload() interface{} {
	return o.Payload
}

func (o *PostPortfolioAccountIDPositionsInvalidateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
