// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAccountAccountIDOrderOrigCustomerOrderIDParams creates a new DeleteAccountAccountIDOrderOrigCustomerOrderIDParams object
// with the default values initialized.
func NewDeleteAccountAccountIDOrderOrigCustomerOrderIDParams() *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams {
	var ()
	return &DeleteAccountAccountIDOrderOrigCustomerOrderIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAccountAccountIDOrderOrigCustomerOrderIDParamsWithTimeout creates a new DeleteAccountAccountIDOrderOrigCustomerOrderIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAccountAccountIDOrderOrigCustomerOrderIDParamsWithTimeout(timeout time.Duration) *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams {
	var ()
	return &DeleteAccountAccountIDOrderOrigCustomerOrderIDParams{

		timeout: timeout,
	}
}

// NewDeleteAccountAccountIDOrderOrigCustomerOrderIDParamsWithContext creates a new DeleteAccountAccountIDOrderOrigCustomerOrderIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAccountAccountIDOrderOrigCustomerOrderIDParamsWithContext(ctx context.Context) *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams {
	var ()
	return &DeleteAccountAccountIDOrderOrigCustomerOrderIDParams{

		Context: ctx,
	}
}

// NewDeleteAccountAccountIDOrderOrigCustomerOrderIDParamsWithHTTPClient creates a new DeleteAccountAccountIDOrderOrigCustomerOrderIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAccountAccountIDOrderOrigCustomerOrderIDParamsWithHTTPClient(client *http.Client) *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams {
	var ()
	return &DeleteAccountAccountIDOrderOrigCustomerOrderIDParams{
		HTTPClient: client,
	}
}

/*DeleteAccountAccountIDOrderOrigCustomerOrderIDParams contains all the parameters to send to the API endpoint
for the delete iserver account account ID order orig customer order ID operation typically these are written to a http.Request
*/
type DeleteAccountAccountIDOrderOrigCustomerOrderIDParams struct {

	/*AccountID
	  account id

	*/
	AccountID string
	/*OrigCustomerOrderID
	  Customer OrderId

	*/
	OrigCustomerOrderID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete iserver account account ID order orig customer order ID params
func (o *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams) WithTimeout(timeout time.Duration) *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete iserver account account ID order orig customer order ID params
func (o *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete iserver account account ID order orig customer order ID params
func (o *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams) WithContext(ctx context.Context) *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete iserver account account ID order orig customer order ID params
func (o *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete iserver account account ID order orig customer order ID params
func (o *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams) WithHTTPClient(client *http.Client) *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete iserver account account ID order orig customer order ID params
func (o *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the delete iserver account account ID order orig customer order ID params
func (o *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams) WithAccountID(accountID string) *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the delete iserver account account ID order orig customer order ID params
func (o *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithOrigCustomerOrderID adds the origCustomerOrderID to the delete iserver account account ID order orig customer order ID params
func (o *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams) WithOrigCustomerOrderID(origCustomerOrderID string) *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams {
	o.SetOrigCustomerOrderID(origCustomerOrderID)
	return o
}

// SetOrigCustomerOrderID adds the origCustomerOrderId to the delete iserver account account ID order orig customer order ID params
func (o *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams) SetOrigCustomerOrderID(origCustomerOrderID string) {
	o.OrigCustomerOrderID = origCustomerOrderID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAccountAccountIDOrderOrigCustomerOrderIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	// path param origCustomerOrderId
	if err := r.SetPathParam("origCustomerOrderId", o.OrigCustomerOrderID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
