// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams creates a new DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams object
// with the default values initialized.
func NewDeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams() *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams {
	var ()
	return &DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParamsWithTimeout creates a new DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParamsWithTimeout(timeout time.Duration) *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams {
	var ()
	return &DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams{

		timeout: timeout,
	}
}

// NewDeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParamsWithContext creates a new DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParamsWithContext(ctx context.Context) *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams {
	var ()
	return &DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams{

		Context: ctx,
	}
}

// NewDeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParamsWithHTTPClient creates a new DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParamsWithHTTPClient(client *http.Client) *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams {
	var ()
	return &DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams{
		HTTPClient: client,
	}
}

/*DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams contains all the parameters to send to the API endpoint
for the delete iserver account account ID order orig customer order ID operation typically these are written to a http.Request
*/
type DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams struct {

	/*AccountID
	  account id

	*/
	AccountID string
	/*OrigCustomerOrderID
	  Customer OrderId

	*/
	OrigCustomerOrderID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete iserver account account ID order orig customer order ID params
func (o *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams) WithTimeout(timeout time.Duration) *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete iserver account account ID order orig customer order ID params
func (o *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete iserver account account ID order orig customer order ID params
func (o *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams) WithContext(ctx context.Context) *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete iserver account account ID order orig customer order ID params
func (o *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete iserver account account ID order orig customer order ID params
func (o *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams) WithHTTPClient(client *http.Client) *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete iserver account account ID order orig customer order ID params
func (o *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the delete iserver account account ID order orig customer order ID params
func (o *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams) WithAccountID(accountID string) *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the delete iserver account account ID order orig customer order ID params
func (o *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithOrigCustomerOrderID adds the origCustomerOrderID to the delete iserver account account ID order orig customer order ID params
func (o *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams) WithOrigCustomerOrderID(origCustomerOrderID string) *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams {
	o.SetOrigCustomerOrderID(origCustomerOrderID)
	return o
}

// SetOrigCustomerOrderID adds the origCustomerOrderId to the delete iserver account account ID order orig customer order ID params
func (o *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams) SetOrigCustomerOrderID(origCustomerOrderID string) {
	o.OrigCustomerOrderID = origCustomerOrderID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteIserverAccountAccountIDOrderOrigCustomerOrderIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	// path param origCustomerOrderId
	if err := r.SetPathParam("origCustomerOrderId", o.OrigCustomerOrderID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
