// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetIserverAccountOrdersParams creates a new GetIserverAccountOrdersParams object
// with the default values initialized.
func NewGetIserverAccountOrdersParams() *GetIserverAccountOrdersParams {

	return &GetIserverAccountOrdersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetIserverAccountOrdersParamsWithTimeout creates a new GetIserverAccountOrdersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetIserverAccountOrdersParamsWithTimeout(timeout time.Duration) *GetIserverAccountOrdersParams {

	return &GetIserverAccountOrdersParams{

		timeout: timeout,
	}
}

// NewGetIserverAccountOrdersParamsWithContext creates a new GetIserverAccountOrdersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetIserverAccountOrdersParamsWithContext(ctx context.Context) *GetIserverAccountOrdersParams {

	return &GetIserverAccountOrdersParams{

		Context: ctx,
	}
}

// NewGetIserverAccountOrdersParamsWithHTTPClient creates a new GetIserverAccountOrdersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetIserverAccountOrdersParamsWithHTTPClient(client *http.Client) *GetIserverAccountOrdersParams {

	return &GetIserverAccountOrdersParams{
		HTTPClient: client,
	}
}

/*GetIserverAccountOrdersParams contains all the parameters to send to the API endpoint
for the get iserver account orders operation typically these are written to a http.Request
*/
type GetIserverAccountOrdersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get iserver account orders params
func (o *GetIserverAccountOrdersParams) WithTimeout(timeout time.Duration) *GetIserverAccountOrdersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get iserver account orders params
func (o *GetIserverAccountOrdersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get iserver account orders params
func (o *GetIserverAccountOrdersParams) WithContext(ctx context.Context) *GetIserverAccountOrdersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get iserver account orders params
func (o *GetIserverAccountOrdersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get iserver account orders params
func (o *GetIserverAccountOrdersParams) WithHTTPClient(client *http.Client) *GetIserverAccountOrdersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get iserver account orders params
func (o *GetIserverAccountOrdersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetIserverAccountOrdersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
