// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostAccountAccountIDOrdersParams creates a new PostAccountAccountIDOrdersParams object
// with the default values initialized.
func NewPostAccountAccountIDOrdersParams() *PostAccountAccountIDOrdersParams {
	var ()
	return &PostAccountAccountIDOrdersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAccountAccountIDOrdersParamsWithTimeout creates a new PostAccountAccountIDOrdersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAccountAccountIDOrdersParamsWithTimeout(timeout time.Duration) *PostAccountAccountIDOrdersParams {
	var ()
	return &PostAccountAccountIDOrdersParams{

		timeout: timeout,
	}
}

// NewPostAccountAccountIDOrdersParamsWithContext creates a new PostAccountAccountIDOrdersParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAccountAccountIDOrdersParamsWithContext(ctx context.Context) *PostAccountAccountIDOrdersParams {
	var ()
	return &PostAccountAccountIDOrdersParams{

		Context: ctx,
	}
}

// NewPostAccountAccountIDOrdersParamsWithHTTPClient creates a new PostAccountAccountIDOrdersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAccountAccountIDOrdersParamsWithHTTPClient(client *http.Client) *PostAccountAccountIDOrdersParams {
	var ()
	return &PostAccountAccountIDOrdersParams{
		HTTPClient: client,
	}
}

/*PostAccountAccountIDOrdersParams contains all the parameters to send to the API endpoint
for the post iserver account account ID orders operation typically these are written to a http.Request
*/
type PostAccountAccountIDOrdersParams struct {

	/*AccountID
	  account id

	*/
	AccountID string
	/*Body
	  order request info

	*/
	Body PostAccountAccountIDOrdersBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post iserver account account ID orders params
func (o *PostAccountAccountIDOrdersParams) WithTimeout(timeout time.Duration) *PostAccountAccountIDOrdersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post iserver account account ID orders params
func (o *PostAccountAccountIDOrdersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post iserver account account ID orders params
func (o *PostAccountAccountIDOrdersParams) WithContext(ctx context.Context) *PostAccountAccountIDOrdersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post iserver account account ID orders params
func (o *PostAccountAccountIDOrdersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post iserver account account ID orders params
func (o *PostAccountAccountIDOrdersParams) WithHTTPClient(client *http.Client) *PostAccountAccountIDOrdersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post iserver account account ID orders params
func (o *PostAccountAccountIDOrdersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the post iserver account account ID orders params
func (o *PostAccountAccountIDOrdersParams) WithAccountID(accountID string) *PostAccountAccountIDOrdersParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the post iserver account account ID orders params
func (o *PostAccountAccountIDOrdersParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithBody adds the body to the post iserver account account ID orders params
func (o *PostAccountAccountIDOrdersParams) WithBody(body PostAccountAccountIDOrdersBody) *PostAccountAccountIDOrdersParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post iserver account account ID orders params
func (o *PostAccountAccountIDOrdersParams) SetBody(body PostAccountAccountIDOrdersBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAccountAccountIDOrdersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
