// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "ibx/models"
)

// NewPostAccountAccountIDOrderWhatifParams creates a new PostAccountAccountIDOrderWhatifParams object
// with the default values initialized.
func NewPostAccountAccountIDOrderWhatifParams() *PostAccountAccountIDOrderWhatifParams {
	var ()
	return &PostAccountAccountIDOrderWhatifParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAccountAccountIDOrderWhatifParamsWithTimeout creates a new PostAccountAccountIDOrderWhatifParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAccountAccountIDOrderWhatifParamsWithTimeout(timeout time.Duration) *PostAccountAccountIDOrderWhatifParams {
	var ()
	return &PostAccountAccountIDOrderWhatifParams{

		timeout: timeout,
	}
}

// NewPostAccountAccountIDOrderWhatifParamsWithContext creates a new PostAccountAccountIDOrderWhatifParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAccountAccountIDOrderWhatifParamsWithContext(ctx context.Context) *PostAccountAccountIDOrderWhatifParams {
	var ()
	return &PostAccountAccountIDOrderWhatifParams{

		Context: ctx,
	}
}

// NewPostAccountAccountIDOrderWhatifParamsWithHTTPClient creates a new PostAccountAccountIDOrderWhatifParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAccountAccountIDOrderWhatifParamsWithHTTPClient(client *http.Client) *PostAccountAccountIDOrderWhatifParams {
	var ()
	return &PostAccountAccountIDOrderWhatifParams{
		HTTPClient: client,
	}
}

/*PostAccountAccountIDOrderWhatifParams contains all the parameters to send to the API endpoint
for the post iserver account account ID order whatif operation typically these are written to a http.Request
*/
type PostAccountAccountIDOrderWhatifParams struct {

	/*AccountID
	  account id

	*/
	AccountID string
	/*Body
	  order info

	*/
	Body *models.OrderRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post iserver account account ID order whatif params
func (o *PostAccountAccountIDOrderWhatifParams) WithTimeout(timeout time.Duration) *PostAccountAccountIDOrderWhatifParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post iserver account account ID order whatif params
func (o *PostAccountAccountIDOrderWhatifParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post iserver account account ID order whatif params
func (o *PostAccountAccountIDOrderWhatifParams) WithContext(ctx context.Context) *PostAccountAccountIDOrderWhatifParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post iserver account account ID order whatif params
func (o *PostAccountAccountIDOrderWhatifParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post iserver account account ID order whatif params
func (o *PostAccountAccountIDOrderWhatifParams) WithHTTPClient(client *http.Client) *PostAccountAccountIDOrderWhatifParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post iserver account account ID order whatif params
func (o *PostAccountAccountIDOrderWhatifParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the post iserver account account ID order whatif params
func (o *PostAccountAccountIDOrderWhatifParams) WithAccountID(accountID string) *PostAccountAccountIDOrderWhatifParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the post iserver account account ID order whatif params
func (o *PostAccountAccountIDOrderWhatifParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithBody adds the body to the post iserver account account ID order whatif params
func (o *PostAccountAccountIDOrderWhatifParams) WithBody(body *models.OrderRequest) *PostAccountAccountIDOrderWhatifParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post iserver account account ID order whatif params
func (o *PostAccountAccountIDOrderWhatifParams) SetBody(body *models.OrderRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAccountAccountIDOrderWhatifParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
