// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// PostIserverAccountAccountIDOrderWhatifReader is a Reader for the PostIserverAccountAccountIDOrderWhatif structure.
type PostIserverAccountAccountIDOrderWhatifReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostIserverAccountAccountIDOrderWhatifReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostIserverAccountAccountIDOrderWhatifOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostIserverAccountAccountIDOrderWhatifOK creates a PostIserverAccountAccountIDOrderWhatifOK with default headers values
func NewPostIserverAccountAccountIDOrderWhatifOK() *PostIserverAccountAccountIDOrderWhatifOK {
	return &PostIserverAccountAccountIDOrderWhatifOK{}
}

/*PostIserverAccountAccountIDOrderWhatifOK handles this case with default header values.

returns an object
*/
type PostIserverAccountAccountIDOrderWhatifOK struct {
	Payload *PostIserverAccountAccountIDOrderWhatifOKBody
}

func (o *PostIserverAccountAccountIDOrderWhatifOK) Error() string {
	return fmt.Sprintf("[POST /iserver/account/{accountId}/order/whatif][%d] postIserverAccountAccountIdOrderWhatifOK  %+v", 200, o.Payload)
}

func (o *PostIserverAccountAccountIDOrderWhatifOK) GetPayload() *PostIserverAccountAccountIDOrderWhatifOKBody {
	return o.Payload
}

func (o *PostIserverAccountAccountIDOrderWhatifOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostIserverAccountAccountIDOrderWhatifOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostIserverAccountAccountIDOrderWhatifOKBody post iserver account account ID order whatif o k body
swagger:model PostIserverAccountAccountIDOrderWhatifOKBody
*/
type PostIserverAccountAccountIDOrderWhatifOKBody struct {

	// amount
	Amount *PostIserverAccountAccountIDOrderWhatifOKBodyAmount `json:"amount,omitempty"`

	// equity
	Equity *PostIserverAccountAccountIDOrderWhatifOKBodyEquity `json:"equity,omitempty"`

	// error
	Error string `json:"error,omitempty"`

	// initial
	Initial *PostIserverAccountAccountIDOrderWhatifOKBodyInitial `json:"initial,omitempty"`

	// maintenance
	Maintenance *PostIserverAccountAccountIDOrderWhatifOKBodyMaintenance `json:"maintenance,omitempty"`

	// warn
	Warn string `json:"warn,omitempty"`
}

// Validate validates this post iserver account account ID order whatif o k body
func (o *PostIserverAccountAccountIDOrderWhatifOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateEquity(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateInitial(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMaintenance(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostIserverAccountAccountIDOrderWhatifOKBody) validateAmount(formats strfmt.Registry) error {

	if swag.IsZero(o.Amount) { // not required
		return nil
	}

	if o.Amount != nil {
		if err := o.Amount.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postIserverAccountAccountIdOrderWhatifOK" + "." + "amount")
			}
			return err
		}
	}

	return nil
}

func (o *PostIserverAccountAccountIDOrderWhatifOKBody) validateEquity(formats strfmt.Registry) error {

	if swag.IsZero(o.Equity) { // not required
		return nil
	}

	if o.Equity != nil {
		if err := o.Equity.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postIserverAccountAccountIdOrderWhatifOK" + "." + "equity")
			}
			return err
		}
	}

	return nil
}

func (o *PostIserverAccountAccountIDOrderWhatifOKBody) validateInitial(formats strfmt.Registry) error {

	if swag.IsZero(o.Initial) { // not required
		return nil
	}

	if o.Initial != nil {
		if err := o.Initial.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postIserverAccountAccountIdOrderWhatifOK" + "." + "initial")
			}
			return err
		}
	}

	return nil
}

func (o *PostIserverAccountAccountIDOrderWhatifOKBody) validateMaintenance(formats strfmt.Registry) error {

	if swag.IsZero(o.Maintenance) { // not required
		return nil
	}

	if o.Maintenance != nil {
		if err := o.Maintenance.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postIserverAccountAccountIdOrderWhatifOK" + "." + "maintenance")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrderWhatifOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrderWhatifOKBody) UnmarshalBinary(b []byte) error {
	var res PostIserverAccountAccountIDOrderWhatifOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostIserverAccountAccountIDOrderWhatifOKBodyAmount post iserver account account ID order whatif o k body amount
swagger:model PostIserverAccountAccountIDOrderWhatifOKBodyAmount
*/
type PostIserverAccountAccountIDOrderWhatifOKBodyAmount struct {

	// for example 23,000 USD
	Amount string `json:"amount,omitempty"`

	// for example 1.1 ... 1.2 USD
	Commission string `json:"commission,omitempty"`

	// total
	Total string `json:"total,omitempty"`
}

// Validate validates this post iserver account account ID order whatif o k body amount
func (o *PostIserverAccountAccountIDOrderWhatifOKBodyAmount) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrderWhatifOKBodyAmount) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrderWhatifOKBodyAmount) UnmarshalBinary(b []byte) error {
	var res PostIserverAccountAccountIDOrderWhatifOKBodyAmount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostIserverAccountAccountIDOrderWhatifOKBodyEquity post iserver account account ID order whatif o k body equity
swagger:model PostIserverAccountAccountIDOrderWhatifOKBodyEquity
*/
type PostIserverAccountAccountIDOrderWhatifOKBodyEquity struct {

	// after
	After string `json:"after,omitempty"`

	// change
	Change string `json:"change,omitempty"`

	// current
	Current string `json:"current,omitempty"`
}

// Validate validates this post iserver account account ID order whatif o k body equity
func (o *PostIserverAccountAccountIDOrderWhatifOKBodyEquity) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrderWhatifOKBodyEquity) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrderWhatifOKBodyEquity) UnmarshalBinary(b []byte) error {
	var res PostIserverAccountAccountIDOrderWhatifOKBodyEquity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostIserverAccountAccountIDOrderWhatifOKBodyInitial post iserver account account ID order whatif o k body initial
swagger:model PostIserverAccountAccountIDOrderWhatifOKBodyInitial
*/
type PostIserverAccountAccountIDOrderWhatifOKBodyInitial struct {

	// after
	After string `json:"after,omitempty"`

	// change
	Change string `json:"change,omitempty"`

	// current
	Current string `json:"current,omitempty"`
}

// Validate validates this post iserver account account ID order whatif o k body initial
func (o *PostIserverAccountAccountIDOrderWhatifOKBodyInitial) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrderWhatifOKBodyInitial) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrderWhatifOKBodyInitial) UnmarshalBinary(b []byte) error {
	var res PostIserverAccountAccountIDOrderWhatifOKBodyInitial
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostIserverAccountAccountIDOrderWhatifOKBodyMaintenance post iserver account account ID order whatif o k body maintenance
swagger:model PostIserverAccountAccountIDOrderWhatifOKBodyMaintenance
*/
type PostIserverAccountAccountIDOrderWhatifOKBodyMaintenance struct {

	// after
	After string `json:"after,omitempty"`

	// change
	Change string `json:"change,omitempty"`

	// current
	Current string `json:"current,omitempty"`
}

// Validate validates this post iserver account account ID order whatif o k body maintenance
func (o *PostIserverAccountAccountIDOrderWhatifOKBodyMaintenance) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrderWhatifOKBodyMaintenance) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrderWhatifOKBodyMaintenance) UnmarshalBinary(b []byte) error {
	var res PostIserverAccountAccountIDOrderWhatifOKBodyMaintenance
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
