// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// PostIserverAccountAccountIDOrderReader is a Reader for the PostIserverAccountAccountIDOrder structure.
type PostIserverAccountAccountIDOrderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostIserverAccountAccountIDOrderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostIserverAccountAccountIDOrderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostIserverAccountAccountIDOrderOK creates a PostIserverAccountAccountIDOrderOK with default headers values
func NewPostIserverAccountAccountIDOrderOK() *PostIserverAccountAccountIDOrderOK {
	return &PostIserverAccountAccountIDOrderOK{}
}

/*PostIserverAccountAccountIDOrderOK handles this case with default header values.

returns an array
*/
type PostIserverAccountAccountIDOrderOK struct {
	Payload []*PostIserverAccountAccountIDOrderOKBodyItems0
}

func (o *PostIserverAccountAccountIDOrderOK) Error() string {
	return fmt.Sprintf("[POST /iserver/account/{accountId}/order][%d] postIserverAccountAccountIdOrderOK  %+v", 200, o.Payload)
}

func (o *PostIserverAccountAccountIDOrderOK) GetPayload() []*PostIserverAccountAccountIDOrderOKBodyItems0 {
	return o.Payload
}

func (o *PostIserverAccountAccountIDOrderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostIserverAccountAccountIDOrderOKBodyItems0 post iserver account account ID order o k body items0
swagger:model PostIserverAccountAccountIDOrderOKBodyItems0
*/
type PostIserverAccountAccountIDOrderOKBodyItems0 struct {

	// id
	ID string `json:"id,omitempty"`

	// Please note here, if the message is a question, you have to reply to question in order to submit
	// the order successfully. See more in the "/iserver/reply/{replyid}" end-point.
	//
	Message []string `json:"message"`
}

// Validate validates this post iserver account account ID order o k body items0
func (o *PostIserverAccountAccountIDOrderOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrderOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrderOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res PostIserverAccountAccountIDOrderOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
