// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "ibx/models"
)

// PostAccountAccountIDOrdersReader is a Reader for the PostAccountAccountIDOrders structure.
type PostAccountAccountIDOrdersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAccountAccountIDOrdersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAccountAccountIDOrdersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAccountAccountIDOrdersOK creates a PostAccountAccountIDOrdersOK with default headers values
func NewPostAccountAccountIDOrdersOK() *PostAccountAccountIDOrdersOK {
	return &PostAccountAccountIDOrdersOK{}
}

/*PostAccountAccountIDOrdersOK handles this case with default header values.

returns an array
*/
type PostAccountAccountIDOrdersOK struct {
	Payload []*PostAccountAccountIDOrdersOKBodyItems0
}

func (o *PostAccountAccountIDOrdersOK) Error() string {
	return fmt.Sprintf("[POST /iserver/account/{accountId}/orders][%d] postAccountAccountIdOrdersOK  %+v", 200, o.Payload)
}

func (o *PostAccountAccountIDOrdersOK) GetPayload() []*PostAccountAccountIDOrdersOKBodyItems0 {
	return o.Payload
}

func (o *PostAccountAccountIDOrdersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostAccountAccountIDOrdersBody post iserver account account ID orders body
swagger:model PostAccountAccountIDOrdersBody
*/
type PostAccountAccountIDOrdersBody struct {

	// Notes for bracket orders: 1. Children orders will not have its own "cOID", so please donot pass "cOID"
	// parameter in child order.Instead, they will have a "parentId" which must be equal to "cOID" of parent.
	// 2. When you cancel a parent order, it will cancel all bracket orders, when you cancel one child order,
	// it will also cancel its sibling order.
	//
	Orders []*models.OrderRequest `json:"orders"`
}

// Validate validates this post iserver account account ID orders body
func (o *PostAccountAccountIDOrdersBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateOrders(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostAccountAccountIDOrdersBody) validateOrders(formats strfmt.Registry) error {

	if swag.IsZero(o.Orders) { // not required
		return nil
	}

	for i := 0; i < len(o.Orders); i++ {
		if swag.IsZero(o.Orders[i]) { // not required
			continue
		}

		if o.Orders[i] != nil {
			if err := o.Orders[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("body" + "." + "orders" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostAccountAccountIDOrdersBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostAccountAccountIDOrdersBody) UnmarshalBinary(b []byte) error {
	var res PostAccountAccountIDOrdersBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostAccountAccountIDOrdersOKBodyItems0 post iserver account account ID orders o k body items0
swagger:model PostAccountAccountIDOrdersOKBodyItems0
*/
type PostAccountAccountIDOrdersOKBodyItems0 struct {

	// id
	ID string `json:"id,omitempty"`

	// Please note here, if the message is a question, you have to reply to question in order to submit
	// the order successfully. See more in the "/iserver/reply/{replyid}" end-point.
	//
	Message []string `json:"message"`
}

// Validate validates this post iserver account account ID orders o k body items0
func (o *PostAccountAccountIDOrdersOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostAccountAccountIDOrdersOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostAccountAccountIDOrdersOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res PostAccountAccountIDOrdersOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
