// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "ibx/models"
)

// PostIserverAccountAccountIDOrdersReader is a Reader for the PostIserverAccountAccountIDOrders structure.
type PostIserverAccountAccountIDOrdersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostIserverAccountAccountIDOrdersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostIserverAccountAccountIDOrdersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostIserverAccountAccountIDOrdersOK creates a PostIserverAccountAccountIDOrdersOK with default headers values
func NewPostIserverAccountAccountIDOrdersOK() *PostIserverAccountAccountIDOrdersOK {
	return &PostIserverAccountAccountIDOrdersOK{}
}

/*PostIserverAccountAccountIDOrdersOK handles this case with default header values.

returns an array
*/
type PostIserverAccountAccountIDOrdersOK struct {
	Payload []*PostIserverAccountAccountIDOrdersOKBodyItems0
}

func (o *PostIserverAccountAccountIDOrdersOK) Error() string {
	return fmt.Sprintf("[POST /iserver/account/{accountId}/orders][%d] postIserverAccountAccountIdOrdersOK  %+v", 200, o.Payload)
}

func (o *PostIserverAccountAccountIDOrdersOK) GetPayload() []*PostIserverAccountAccountIDOrdersOKBodyItems0 {
	return o.Payload
}

func (o *PostIserverAccountAccountIDOrdersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostIserverAccountAccountIDOrdersBody post iserver account account ID orders body
swagger:model PostIserverAccountAccountIDOrdersBody
*/
type PostIserverAccountAccountIDOrdersBody struct {

	// Notes for bracket orders: 1. Children orders will not have its own "cOID", so please donot pass "cOID"
	// parameter in child order.Instead, they will have a "parentId" which must be equal to "cOID" of parent.
	// 2. When you cancel a parent order, it will cancel all bracket orders, when you cancel one child order,
	// it will also cancel its sibling order.
	//
	Orders []*models.OrderRequest `json:"orders"`
}

// Validate validates this post iserver account account ID orders body
func (o *PostIserverAccountAccountIDOrdersBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateOrders(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostIserverAccountAccountIDOrdersBody) validateOrders(formats strfmt.Registry) error {

	if swag.IsZero(o.Orders) { // not required
		return nil
	}

	for i := 0; i < len(o.Orders); i++ {
		if swag.IsZero(o.Orders[i]) { // not required
			continue
		}

		if o.Orders[i] != nil {
			if err := o.Orders[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("body" + "." + "orders" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrdersBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrdersBody) UnmarshalBinary(b []byte) error {
	var res PostIserverAccountAccountIDOrdersBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostIserverAccountAccountIDOrdersOKBodyItems0 post iserver account account ID orders o k body items0
swagger:model PostIserverAccountAccountIDOrdersOKBodyItems0
*/
type PostIserverAccountAccountIDOrdersOKBodyItems0 struct {

	// id
	ID string `json:"id,omitempty"`

	// Please note here, if the message is a question, you have to reply to question in order to submit
	// the order successfully. See more in the "/iserver/reply/{replyid}" end-point.
	//
	Message []string `json:"message"`
}

// Validate validates this post iserver account account ID orders o k body items0
func (o *PostIserverAccountAccountIDOrdersOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrdersOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrdersOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res PostIserverAccountAccountIDOrdersOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
