// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "ibx/models"
)

// NewPostAccountAccountIDOrderOrigCustomerOrderIDParams creates a new PostAccountAccountIDOrderOrigCustomerOrderIDParams object
// with the default values initialized.
func NewPostAccountAccountIDOrderOrigCustomerOrderIDParams() *PostAccountAccountIDOrderOrigCustomerOrderIDParams {
	var ()
	return &PostAccountAccountIDOrderOrigCustomerOrderIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAccountAccountIDOrderOrigCustomerOrderIDParamsWithTimeout creates a new PostAccountAccountIDOrderOrigCustomerOrderIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAccountAccountIDOrderOrigCustomerOrderIDParamsWithTimeout(timeout time.Duration) *PostAccountAccountIDOrderOrigCustomerOrderIDParams {
	var ()
	return &PostAccountAccountIDOrderOrigCustomerOrderIDParams{

		timeout: timeout,
	}
}

// NewPostAccountAccountIDOrderOrigCustomerOrderIDParamsWithContext creates a new PostAccountAccountIDOrderOrigCustomerOrderIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAccountAccountIDOrderOrigCustomerOrderIDParamsWithContext(ctx context.Context) *PostAccountAccountIDOrderOrigCustomerOrderIDParams {
	var ()
	return &PostAccountAccountIDOrderOrigCustomerOrderIDParams{

		Context: ctx,
	}
}

// NewPostAccountAccountIDOrderOrigCustomerOrderIDParamsWithHTTPClient creates a new PostAccountAccountIDOrderOrigCustomerOrderIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAccountAccountIDOrderOrigCustomerOrderIDParamsWithHTTPClient(client *http.Client) *PostAccountAccountIDOrderOrigCustomerOrderIDParams {
	var ()
	return &PostAccountAccountIDOrderOrigCustomerOrderIDParams{
		HTTPClient: client,
	}
}

/*PostAccountAccountIDOrderOrigCustomerOrderIDParams contains all the parameters to send to the API endpoint
for the post iserver account account ID order orig customer order ID operation typically these are written to a http.Request
*/
type PostAccountAccountIDOrderOrigCustomerOrderIDParams struct {

	/*AccountID
	  account id

	*/
	AccountID string
	/*Body
	  modify-order request

	*/
	Body *models.ModifyOrder
	/*OrigCustomerOrderID
	  Customer OrderId

	*/
	OrigCustomerOrderID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post iserver account account ID order orig customer order ID params
func (o *PostAccountAccountIDOrderOrigCustomerOrderIDParams) WithTimeout(timeout time.Duration) *PostAccountAccountIDOrderOrigCustomerOrderIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post iserver account account ID order orig customer order ID params
func (o *PostAccountAccountIDOrderOrigCustomerOrderIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post iserver account account ID order orig customer order ID params
func (o *PostAccountAccountIDOrderOrigCustomerOrderIDParams) WithContext(ctx context.Context) *PostAccountAccountIDOrderOrigCustomerOrderIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post iserver account account ID order orig customer order ID params
func (o *PostAccountAccountIDOrderOrigCustomerOrderIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post iserver account account ID order orig customer order ID params
func (o *PostAccountAccountIDOrderOrigCustomerOrderIDParams) WithHTTPClient(client *http.Client) *PostAccountAccountIDOrderOrigCustomerOrderIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post iserver account account ID order orig customer order ID params
func (o *PostAccountAccountIDOrderOrigCustomerOrderIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the post iserver account account ID order orig customer order ID params
func (o *PostAccountAccountIDOrderOrigCustomerOrderIDParams) WithAccountID(accountID string) *PostAccountAccountIDOrderOrigCustomerOrderIDParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the post iserver account account ID order orig customer order ID params
func (o *PostAccountAccountIDOrderOrigCustomerOrderIDParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithBody adds the body to the post iserver account account ID order orig customer order ID params
func (o *PostAccountAccountIDOrderOrigCustomerOrderIDParams) WithBody(body *models.ModifyOrder) *PostAccountAccountIDOrderOrigCustomerOrderIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post iserver account account ID order orig customer order ID params
func (o *PostAccountAccountIDOrderOrigCustomerOrderIDParams) SetBody(body *models.ModifyOrder) {
	o.Body = body
}

// WithOrigCustomerOrderID adds the origCustomerOrderID to the post iserver account account ID order orig customer order ID params
func (o *PostAccountAccountIDOrderOrigCustomerOrderIDParams) WithOrigCustomerOrderID(origCustomerOrderID string) *PostAccountAccountIDOrderOrigCustomerOrderIDParams {
	o.SetOrigCustomerOrderID(origCustomerOrderID)
	return o
}

// SetOrigCustomerOrderID adds the origCustomerOrderId to the post iserver account account ID order orig customer order ID params
func (o *PostAccountAccountIDOrderOrigCustomerOrderIDParams) SetOrigCustomerOrderID(origCustomerOrderID string) {
	o.OrigCustomerOrderID = origCustomerOrderID
}

// WriteToRequest writes these params to a swagger request
func (o *PostAccountAccountIDOrderOrigCustomerOrderIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param origCustomerOrderId
	if err := r.SetPathParam("origCustomerOrderId", o.OrigCustomerOrderID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
