// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "learn2/models"
)

// NewPostIserverAccountAccountIDOrderWhatifParams creates a new PostIserverAccountAccountIDOrderWhatifParams object
// with the default values initialized.
func NewPostIserverAccountAccountIDOrderWhatifParams() *PostIserverAccountAccountIDOrderWhatifParams {
	var ()
	return &PostIserverAccountAccountIDOrderWhatifParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostIserverAccountAccountIDOrderWhatifParamsWithTimeout creates a new PostIserverAccountAccountIDOrderWhatifParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostIserverAccountAccountIDOrderWhatifParamsWithTimeout(timeout time.Duration) *PostIserverAccountAccountIDOrderWhatifParams {
	var ()
	return &PostIserverAccountAccountIDOrderWhatifParams{

		timeout: timeout,
	}
}

// NewPostIserverAccountAccountIDOrderWhatifParamsWithContext creates a new PostIserverAccountAccountIDOrderWhatifParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostIserverAccountAccountIDOrderWhatifParamsWithContext(ctx context.Context) *PostIserverAccountAccountIDOrderWhatifParams {
	var ()
	return &PostIserverAccountAccountIDOrderWhatifParams{

		Context: ctx,
	}
}

// NewPostIserverAccountAccountIDOrderWhatifParamsWithHTTPClient creates a new PostIserverAccountAccountIDOrderWhatifParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostIserverAccountAccountIDOrderWhatifParamsWithHTTPClient(client *http.Client) *PostIserverAccountAccountIDOrderWhatifParams {
	var ()
	return &PostIserverAccountAccountIDOrderWhatifParams{
		HTTPClient: client,
	}
}

/*PostIserverAccountAccountIDOrderWhatifParams contains all the parameters to send to the API endpoint
for the post iserver account account ID order whatif operation typically these are written to a http.Request
*/
type PostIserverAccountAccountIDOrderWhatifParams struct {

	/*AccountID
	  account id

	*/
	AccountID string
	/*Body
	  order info

	*/
	Body *models.OrderRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post iserver account account ID order whatif params
func (o *PostIserverAccountAccountIDOrderWhatifParams) WithTimeout(timeout time.Duration) *PostIserverAccountAccountIDOrderWhatifParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post iserver account account ID order whatif params
func (o *PostIserverAccountAccountIDOrderWhatifParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post iserver account account ID order whatif params
func (o *PostIserverAccountAccountIDOrderWhatifParams) WithContext(ctx context.Context) *PostIserverAccountAccountIDOrderWhatifParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post iserver account account ID order whatif params
func (o *PostIserverAccountAccountIDOrderWhatifParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post iserver account account ID order whatif params
func (o *PostIserverAccountAccountIDOrderWhatifParams) WithHTTPClient(client *http.Client) *PostIserverAccountAccountIDOrderWhatifParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post iserver account account ID order whatif params
func (o *PostIserverAccountAccountIDOrderWhatifParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the post iserver account account ID order whatif params
func (o *PostIserverAccountAccountIDOrderWhatifParams) WithAccountID(accountID string) *PostIserverAccountAccountIDOrderWhatifParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the post iserver account account ID order whatif params
func (o *PostIserverAccountAccountIDOrderWhatifParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WithBody adds the body to the post iserver account account ID order whatif params
func (o *PostIserverAccountAccountIDOrderWhatifParams) WithBody(body *models.OrderRequest) *PostIserverAccountAccountIDOrderWhatifParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post iserver account account ID order whatif params
func (o *PostIserverAccountAccountIDOrderWhatifParams) SetBody(body *models.OrderRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostIserverAccountAccountIDOrderWhatifParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
