// Code generated by go-swagger; DO NOT EDIT.

package order

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// PostIserverAccountAccountIDOrderOrigCustomerOrderIDReader is a Reader for the PostIserverAccountAccountIDOrderOrigCustomerOrderID structure.
type PostIserverAccountAccountIDOrderOrigCustomerOrderIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostIserverAccountAccountIDOrderOrigCustomerOrderIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostIserverAccountAccountIDOrderOrigCustomerOrderIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostIserverAccountAccountIDOrderOrigCustomerOrderIDOK creates a PostIserverAccountAccountIDOrderOrigCustomerOrderIDOK with default headers values
func NewPostIserverAccountAccountIDOrderOrigCustomerOrderIDOK() *PostIserverAccountAccountIDOrderOrigCustomerOrderIDOK {
	return &PostIserverAccountAccountIDOrderOrigCustomerOrderIDOK{}
}

/*PostIserverAccountAccountIDOrderOrigCustomerOrderIDOK handles this case with default header values.

returns an array
*/
type PostIserverAccountAccountIDOrderOrigCustomerOrderIDOK struct {
	Payload []*PostIserverAccountAccountIDOrderOrigCustomerOrderIDOKBodyItems0
}

func (o *PostIserverAccountAccountIDOrderOrigCustomerOrderIDOK) Error() string {
	return fmt.Sprintf("[POST /iserver/account/{accountId}/order/{origCustomerOrderId}][%d] postIserverAccountAccountIdOrderOrigCustomerOrderIdOK  %+v", 200, o.Payload)
}

func (o *PostIserverAccountAccountIDOrderOrigCustomerOrderIDOK) GetPayload() []*PostIserverAccountAccountIDOrderOrigCustomerOrderIDOKBodyItems0 {
	return o.Payload
}

func (o *PostIserverAccountAccountIDOrderOrigCustomerOrderIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostIserverAccountAccountIDOrderOrigCustomerOrderIDOKBodyItems0 post iserver account account ID order orig customer order ID o k body items0
swagger:model PostIserverAccountAccountIDOrderOrigCustomerOrderIDOKBodyItems0
*/
type PostIserverAccountAccountIDOrderOrigCustomerOrderIDOKBodyItems0 struct {

	// local order id
	LocalOrderID string `json:"local_order_id,omitempty"`

	// order id
	OrderID string `json:"order_id,omitempty"`

	// order status
	OrderStatus string `json:"order_status,omitempty"`
}

// Validate validates this post iserver account account ID order orig customer order ID o k body items0
func (o *PostIserverAccountAccountIDOrderOrigCustomerOrderIDOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrderOrigCustomerOrderIDOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostIserverAccountAccountIDOrderOrigCustomerOrderIDOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res PostIserverAccountAccountIDOrderOrigCustomerOrderIDOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
