// Code generated by go-swagger; DO NOT EDIT.

package contract

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "learn2/models"
)

// GetTrsrvFuturesReader is a Reader for the GetTrsrvFutures structure.
type GetTrsrvFuturesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTrsrvFuturesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTrsrvFuturesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetTrsrvFuturesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTrsrvFuturesOK creates a GetTrsrvFuturesOK with default headers values
func NewGetTrsrvFuturesOK() *GetTrsrvFuturesOK {
	return &GetTrsrvFuturesOK{}
}

/*GetTrsrvFuturesOK handles this case with default header values.

returns an object with symbol and and array of its future contracts
*/
type GetTrsrvFuturesOK struct {
	Payload *GetTrsrvFuturesOKBody
}

func (o *GetTrsrvFuturesOK) Error() string {
	return fmt.Sprintf("[GET /trsrv/futures][%d] getTrsrvFuturesOK  %+v", 200, o.Payload)
}

func (o *GetTrsrvFuturesOK) GetPayload() *GetTrsrvFuturesOKBody {
	return o.Payload
}

func (o *GetTrsrvFuturesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetTrsrvFuturesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTrsrvFuturesInternalServerError creates a GetTrsrvFuturesInternalServerError with default headers values
func NewGetTrsrvFuturesInternalServerError() *GetTrsrvFuturesInternalServerError {
	return &GetTrsrvFuturesInternalServerError{}
}

/*GetTrsrvFuturesInternalServerError handles this case with default header values.

error while processing the request
*/
type GetTrsrvFuturesInternalServerError struct {
	Payload *GetTrsrvFuturesInternalServerErrorBody
}

func (o *GetTrsrvFuturesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /trsrv/futures][%d] getTrsrvFuturesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetTrsrvFuturesInternalServerError) GetPayload() *GetTrsrvFuturesInternalServerErrorBody {
	return o.Payload
}

func (o *GetTrsrvFuturesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetTrsrvFuturesInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetTrsrvFuturesInternalServerErrorBody get trsrv futures internal server error body
swagger:model GetTrsrvFuturesInternalServerErrorBody
*/
type GetTrsrvFuturesInternalServerErrorBody struct {

	// error
	Error string `json:"error,omitempty"`
}

// Validate validates this get trsrv futures internal server error body
func (o *GetTrsrvFuturesInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetTrsrvFuturesInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTrsrvFuturesInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res GetTrsrvFuturesInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetTrsrvFuturesOKBody get trsrv futures o k body
swagger:model GetTrsrvFuturesOKBody
*/
type GetTrsrvFuturesOKBody struct {

	// symbol
	Symbol models.Futures `json:"symbol,omitempty"`
}

// Validate validates this get trsrv futures o k body
func (o *GetTrsrvFuturesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateSymbol(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTrsrvFuturesOKBody) validateSymbol(formats strfmt.Registry) error {

	if swag.IsZero(o.Symbol) { // not required
		return nil
	}

	if err := o.Symbol.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("getTrsrvFuturesOK" + "." + "symbol")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetTrsrvFuturesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetTrsrvFuturesOKBody) UnmarshalBinary(b []byte) error {
	var res GetTrsrvFuturesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
