// Code generated by go-swagger; DO NOT EDIT.

package contract

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "ibx/models"
)

// GetIserverContractConidInfoReader is a Reader for the GetIserverContractConidInfo structure.
type GetIserverContractConidInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIserverContractConidInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetIserverContractConidInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetIserverContractConidInfoOK creates a GetIserverContractConidInfoOK with default headers values
func NewGetIserverContractConidInfoOK() *GetIserverContractConidInfoOK {
	return &GetIserverContractConidInfoOK{}
}

/*GetIserverContractConidInfoOK handles this case with default header values.

returns an object
*/
type GetIserverContractConidInfoOK struct {
	Payload *models.Contract
}

func (o *GetIserverContractConidInfoOK) Error() string {
	return fmt.Sprintf("[GET /iserver/contract/{conid}/info][%d] getIserverContractConidInfoOK  %+v", 200, o.Payload)
}

func (o *GetIserverContractConidInfoOK) GetPayload() *models.Contract {
	return o.Payload
}

func (o *GetIserverContractConidInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Contract)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
