// Code generated by go-swagger; DO NOT EDIT.

package contract

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"github.com/go-openapi/runtime"
	strfmt "github.com/go-openapi/strfmt"
	models "ibx/models"
	"io"
)

// GetContractConidInfoReader is a Reader for the GetContractConidInfo structure.
type GetContractConidInfoReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetContractConidInfoReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetContractConidInfoOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetContractConidInfoOK creates a GetContractConidInfoOK with default headers values
func NewGetContractConidInfoOK() *GetContractConidInfoOK {
	return &GetContractConidInfoOK{}
}

/*GetContractConidInfoOK handles this case with default header values.

returns an object
*/
type GetContractConidInfoOK struct {
	Payload *models.Contract
}

func (o *GetContractConidInfoOK) Error() string {
	return fmt.Sprintf("[GET /iserver/contract/{conid}/info][%d] getContractConidInfoOK  %+v", 200, o.Payload)
}

func (o *GetContractConidInfoOK) GetPayload() *models.Contract {
	return o.Payload
}

func (o *GetContractConidInfoOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Contract)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
