// Code generated by go-swagger; DO NOT EDIT.

package contract

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetContractConidInfoParams creates a new GetContractConidInfoParams object
// with the default values initialized.
func NewGetContractConidInfoParams() *GetContractConidInfoParams {
	var ()
	return &GetContractConidInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetContractConidInfoParamsWithTimeout creates a new GetContractConidInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetContractConidInfoParamsWithTimeout(timeout time.Duration) *GetContractConidInfoParams {
	var ()
	return &GetContractConidInfoParams{

		timeout: timeout,
	}
}

// NewGetContractConidInfoParamsWithContext creates a new GetContractConidInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetContractConidInfoParamsWithContext(ctx context.Context) *GetContractConidInfoParams {
	var ()
	return &GetContractConidInfoParams{

		Context: ctx,
	}
}

// NewGetContractConidInfoParamsWithHTTPClient creates a new GetContractConidInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetContractConidInfoParamsWithHTTPClient(client *http.Client) *GetContractConidInfoParams {
	var ()
	return &GetContractConidInfoParams{
		HTTPClient: client,
	}
}

/*GetContractConidInfoParams contains all the parameters to send to the API endpoint
for the get iserver contract conid info operation typically these are written to a http.Request
*/
type GetContractConidInfoParams struct {

	/*Conid
	  contract id

	*/
	Conid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get iserver contract conid info params
func (o *GetContractConidInfoParams) WithTimeout(timeout time.Duration) *GetContractConidInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get iserver contract conid info params
func (o *GetContractConidInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get iserver contract conid info params
func (o *GetContractConidInfoParams) WithContext(ctx context.Context) *GetContractConidInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get iserver contract conid info params
func (o *GetContractConidInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get iserver contract conid info params
func (o *GetContractConidInfoParams) WithHTTPClient(client *http.Client) *GetContractConidInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get iserver contract conid info params
func (o *GetContractConidInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConid adds the conid to the get iserver contract conid info params
func (o *GetContractConidInfoParams) WithConid(conid string) *GetContractConidInfoParams {
	o.SetConid(conid)
	return o
}

// SetConid adds the conid to the get iserver contract conid info params
func (o *GetContractConidInfoParams) SetConid(conid string) {
	o.Conid = conid
}

// WriteToRequest writes these params to a swagger request
func (o *GetContractConidInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param conid
	if err := r.SetPathParam("conid", o.Conid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
