// Code generated by go-swagger; DO NOT EDIT.

package portfolio_analyst

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "learn2/models"
)

// PostPaPerformanceReader is a Reader for the PostPaPerformance structure.
type PostPaPerformanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostPaPerformanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostPaPerformanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostPaPerformanceOK creates a PostPaPerformanceOK with default headers values
func NewPostPaPerformanceOK() *PostPaPerformanceOK {
	return &PostPaPerformanceOK{}
}

/*PostPaPerformanceOK handles this case with default header values.

returns an object
*/
type PostPaPerformanceOK struct {
	Payload *models.Performance
}

func (o *PostPaPerformanceOK) Error() string {
	return fmt.Sprintf("[POST /pa/performance][%d] postPaPerformanceOK  %+v", 200, o.Payload)
}

func (o *PostPaPerformanceOK) GetPayload() *models.Performance {
	return o.Payload
}

func (o *PostPaPerformanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Performance)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostPaPerformanceBody post pa performance body
swagger:model PostPaPerformanceBody
*/
type PostPaPerformanceBody struct {

	// acct ids
	AcctIds []string `json:"acctIds"`
}

// Validate validates this post pa performance body
func (o *PostPaPerformanceBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostPaPerformanceBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostPaPerformanceBody) UnmarshalBinary(b []byte) error {
	var res PostPaPerformanceBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
