// Code generated by go-swagger; DO NOT EDIT.

package portfolio_analyst

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostPaPerformanceParams creates a new PostPaPerformanceParams object
// with the default values initialized.
func NewPostPaPerformanceParams() *PostPaPerformanceParams {
	var ()
	return &PostPaPerformanceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostPaPerformanceParamsWithTimeout creates a new PostPaPerformanceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostPaPerformanceParamsWithTimeout(timeout time.Duration) *PostPaPerformanceParams {
	var ()
	return &PostPaPerformanceParams{

		timeout: timeout,
	}
}

// NewPostPaPerformanceParamsWithContext creates a new PostPaPerformanceParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostPaPerformanceParamsWithContext(ctx context.Context) *PostPaPerformanceParams {
	var ()
	return &PostPaPerformanceParams{

		Context: ctx,
	}
}

// NewPostPaPerformanceParamsWithHTTPClient creates a new PostPaPerformanceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostPaPerformanceParamsWithHTTPClient(client *http.Client) *PostPaPerformanceParams {
	var ()
	return &PostPaPerformanceParams{
		HTTPClient: client,
	}
}

/*PostPaPerformanceParams contains all the parameters to send to the API endpoint
for the post pa performance operation typically these are written to a http.Request
*/
type PostPaPerformanceParams struct {

	/*Body
	  an array of account ids

	*/
	Body PostPaPerformanceBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post pa performance params
func (o *PostPaPerformanceParams) WithTimeout(timeout time.Duration) *PostPaPerformanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post pa performance params
func (o *PostPaPerformanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post pa performance params
func (o *PostPaPerformanceParams) WithContext(ctx context.Context) *PostPaPerformanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post pa performance params
func (o *PostPaPerformanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post pa performance params
func (o *PostPaPerformanceParams) WithHTTPClient(client *http.Client) *PostPaPerformanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post pa performance params
func (o *PostPaPerformanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post pa performance params
func (o *PostPaPerformanceParams) WithBody(body PostPaPerformanceBody) *PostPaPerformanceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post pa performance params
func (o *PostPaPerformanceParams) SetBody(body PostPaPerformanceBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostPaPerformanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
