// Code generated by go-swagger; DO NOT EDIT.

package portfolio_analyst

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostPaSummaryParams creates a new PostPaSummaryParams object
// with the default values initialized.
func NewPostPaSummaryParams() *PostPaSummaryParams {
	var ()
	return &PostPaSummaryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostPaSummaryParamsWithTimeout creates a new PostPaSummaryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostPaSummaryParamsWithTimeout(timeout time.Duration) *PostPaSummaryParams {
	var ()
	return &PostPaSummaryParams{

		timeout: timeout,
	}
}

// NewPostPaSummaryParamsWithContext creates a new PostPaSummaryParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostPaSummaryParamsWithContext(ctx context.Context) *PostPaSummaryParams {
	var ()
	return &PostPaSummaryParams{

		Context: ctx,
	}
}

// NewPostPaSummaryParamsWithHTTPClient creates a new PostPaSummaryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostPaSummaryParamsWithHTTPClient(client *http.Client) *PostPaSummaryParams {
	var ()
	return &PostPaSummaryParams{
		HTTPClient: client,
	}
}

/*PostPaSummaryParams contains all the parameters to send to the API endpoint
for the post pa summary operation typically these are written to a http.Request
*/
type PostPaSummaryParams struct {

	/*Body
	  an array of account ids

	*/
	Body PostPaSummaryBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post pa summary params
func (o *PostPaSummaryParams) WithTimeout(timeout time.Duration) *PostPaSummaryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post pa summary params
func (o *PostPaSummaryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post pa summary params
func (o *PostPaSummaryParams) WithContext(ctx context.Context) *PostPaSummaryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post pa summary params
func (o *PostPaSummaryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post pa summary params
func (o *PostPaSummaryParams) WithHTTPClient(client *http.Client) *PostPaSummaryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post pa summary params
func (o *PostPaSummaryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post pa summary params
func (o *PostPaSummaryParams) WithBody(body PostPaSummaryBody) *PostPaSummaryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post pa summary params
func (o *PostPaSummaryParams) SetBody(body PostPaSummaryBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostPaSummaryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
