// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPortfolioAccountIDSummaryParams creates a new GetPortfolioAccountIDSummaryParams object
// with the default values initialized.
func NewGetPortfolioAccountIDSummaryParams() *GetPortfolioAccountIDSummaryParams {
	var ()
	return &GetPortfolioAccountIDSummaryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPortfolioAccountIDSummaryParamsWithTimeout creates a new GetPortfolioAccountIDSummaryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPortfolioAccountIDSummaryParamsWithTimeout(timeout time.Duration) *GetPortfolioAccountIDSummaryParams {
	var ()
	return &GetPortfolioAccountIDSummaryParams{

		timeout: timeout,
	}
}

// NewGetPortfolioAccountIDSummaryParamsWithContext creates a new GetPortfolioAccountIDSummaryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPortfolioAccountIDSummaryParamsWithContext(ctx context.Context) *GetPortfolioAccountIDSummaryParams {
	var ()
	return &GetPortfolioAccountIDSummaryParams{

		Context: ctx,
	}
}

// NewGetPortfolioAccountIDSummaryParamsWithHTTPClient creates a new GetPortfolioAccountIDSummaryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPortfolioAccountIDSummaryParamsWithHTTPClient(client *http.Client) *GetPortfolioAccountIDSummaryParams {
	var ()
	return &GetPortfolioAccountIDSummaryParams{
		HTTPClient: client,
	}
}

/*GetPortfolioAccountIDSummaryParams contains all the parameters to send to the API endpoint
for the get portfolio account ID summary operation typically these are written to a http.Request
*/
type GetPortfolioAccountIDSummaryParams struct {

	/*AccountID
	  account id

	*/
	AccountID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get portfolio account ID summary params
func (o *GetPortfolioAccountIDSummaryParams) WithTimeout(timeout time.Duration) *GetPortfolioAccountIDSummaryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get portfolio account ID summary params
func (o *GetPortfolioAccountIDSummaryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get portfolio account ID summary params
func (o *GetPortfolioAccountIDSummaryParams) WithContext(ctx context.Context) *GetPortfolioAccountIDSummaryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get portfolio account ID summary params
func (o *GetPortfolioAccountIDSummaryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get portfolio account ID summary params
func (o *GetPortfolioAccountIDSummaryParams) WithHTTPClient(client *http.Client) *GetPortfolioAccountIDSummaryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get portfolio account ID summary params
func (o *GetPortfolioAccountIDSummaryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get portfolio account ID summary params
func (o *GetPortfolioAccountIDSummaryParams) WithAccountID(accountID string) *GetPortfolioAccountIDSummaryParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get portfolio account ID summary params
func (o *GetPortfolioAccountIDSummaryParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPortfolioAccountIDSummaryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param accountId
	if err := r.SetPathParam("accountId", o.AccountID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
