// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPortfolioSubaccountsParams creates a new GetPortfolioSubaccountsParams object
// with the default values initialized.
func NewGetPortfolioSubaccountsParams() *GetPortfolioSubaccountsParams {

	return &GetPortfolioSubaccountsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPortfolioSubaccountsParamsWithTimeout creates a new GetPortfolioSubaccountsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPortfolioSubaccountsParamsWithTimeout(timeout time.Duration) *GetPortfolioSubaccountsParams {

	return &GetPortfolioSubaccountsParams{

		timeout: timeout,
	}
}

// NewGetPortfolioSubaccountsParamsWithContext creates a new GetPortfolioSubaccountsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPortfolioSubaccountsParamsWithContext(ctx context.Context) *GetPortfolioSubaccountsParams {

	return &GetPortfolioSubaccountsParams{

		Context: ctx,
	}
}

// NewGetPortfolioSubaccountsParamsWithHTTPClient creates a new GetPortfolioSubaccountsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPortfolioSubaccountsParamsWithHTTPClient(client *http.Client) *GetPortfolioSubaccountsParams {

	return &GetPortfolioSubaccountsParams{
		HTTPClient: client,
	}
}

/*GetPortfolioSubaccountsParams contains all the parameters to send to the API endpoint
for the get portfolio subaccounts operation typically these are written to a http.Request
*/
type GetPortfolioSubaccountsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get portfolio subaccounts params
func (o *GetPortfolioSubaccountsParams) WithTimeout(timeout time.Duration) *GetPortfolioSubaccountsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get portfolio subaccounts params
func (o *GetPortfolioSubaccountsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get portfolio subaccounts params
func (o *GetPortfolioSubaccountsParams) WithContext(ctx context.Context) *GetPortfolioSubaccountsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get portfolio subaccounts params
func (o *GetPortfolioSubaccountsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get portfolio subaccounts params
func (o *GetPortfolioSubaccountsParams) WithHTTPClient(client *http.Client) *GetPortfolioSubaccountsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get portfolio subaccounts params
func (o *GetPortfolioSubaccountsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPortfolioSubaccountsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
