// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "ibx/models"
)

// GetPortfolioSubaccountsReader is a Reader for the GetPortfolioSubaccounts structure.
type GetPortfolioSubaccountsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPortfolioSubaccountsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPortfolioSubaccountsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPortfolioSubaccountsOK creates a GetPortfolioSubaccountsOK with default headers values
func NewGetPortfolioSubaccountsOK() *GetPortfolioSubaccountsOK {
	return &GetPortfolioSubaccountsOK{}
}

/*GetPortfolioSubaccountsOK handles this case with default header values.

An array
*/
type GetPortfolioSubaccountsOK struct {
	Payload *models.Account
}

func (o *GetPortfolioSubaccountsOK) Error() string {
	return fmt.Sprintf("[GET /portfolio/subaccounts][%d] getPortfolioSubaccountsOK  %+v", 200, o.Payload)
}

func (o *GetPortfolioSubaccountsOK) GetPayload() *models.Account {
	return o.Payload
}

func (o *GetPortfolioSubaccountsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Account)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
