// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "learn2/models"
)

// GetPortfolioAccountIDMetaReader is a Reader for the GetPortfolioAccountIDMeta structure.
type GetPortfolioAccountIDMetaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPortfolioAccountIDMetaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPortfolioAccountIDMetaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPortfolioAccountIDMetaOK creates a GetPortfolioAccountIDMetaOK with default headers values
func NewGetPortfolioAccountIDMetaOK() *GetPortfolioAccountIDMetaOK {
	return &GetPortfolioAccountIDMetaOK{}
}

/*GetPortfolioAccountIDMetaOK handles this case with default header values.

An object
*/
type GetPortfolioAccountIDMetaOK struct {
	Payload models.Accounts
}

func (o *GetPortfolioAccountIDMetaOK) Error() string {
	return fmt.Sprintf("[GET /portfolio/{accountId}/meta][%d] getPortfolioAccountIdMetaOK  %+v", 200, o.Payload)
}

func (o *GetPortfolioAccountIDMetaOK) GetPayload() models.Accounts {
	return o.Payload
}

func (o *GetPortfolioAccountIDMetaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
