// Code generated by go-swagger; DO NOT EDIT.

package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "ibx/models"
)

// NewPostAccountParams creates a new PostAccountParams object
// with the default values initialized.
func NewPostAccountParams() *PostAccountParams {
	var ()
	return &PostAccountParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAccountParamsWithTimeout creates a new PostAccountParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAccountParamsWithTimeout(timeout time.Duration) *PostAccountParams {
	var ()
	return &PostAccountParams{

		timeout: timeout,
	}
}

// NewPostAccountParamsWithContext creates a new PostAccountParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAccountParamsWithContext(ctx context.Context) *PostAccountParams {
	var ()
	return &PostAccountParams{

		Context: ctx,
	}
}

// NewPostAccountParamsWithHTTPClient creates a new PostAccountParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAccountParamsWithHTTPClient(client *http.Client) *PostAccountParams {
	var ()
	return &PostAccountParams{
		HTTPClient: client,
	}
}

/*PostAccountParams contains all the parameters to send to the API endpoint
for the post iserver account operation typically these are written to a http.Request
*/
type PostAccountParams struct {

	/*Body
	  account id

	*/
	Body *models.SetAccount

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post iserver account params
func (o *PostAccountParams) WithTimeout(timeout time.Duration) *PostAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post iserver account params
func (o *PostAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post iserver account params
func (o *PostAccountParams) WithContext(ctx context.Context) *PostAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post iserver account params
func (o *PostAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post iserver account params
func (o *PostAccountParams) WithHTTPClient(client *http.Client) *PostAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post iserver account params
func (o *PostAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post iserver account params
func (o *PostAccountParams) WithBody(body *models.SetAccount) *PostAccountParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post iserver account params
func (o *PostAccountParams) SetBody(body *models.SetAccount) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
