// Code generated by go-swagger; DO NOT EDIT.

package pn_l

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// GetIserverAccountPnlPartitionedReader is a Reader for the GetIserverAccountPnlPartitioned structure.
type GetIserverAccountPnlPartitionedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIserverAccountPnlPartitionedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetIserverAccountPnlPartitionedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetIserverAccountPnlPartitionedOK creates a GetIserverAccountPnlPartitionedOK with default headers values
func NewGetIserverAccountPnlPartitionedOK() *GetIserverAccountPnlPartitionedOK {
	return &GetIserverAccountPnlPartitionedOK{}
}

/*GetIserverAccountPnlPartitionedOK handles this case with default header values.

An object containing account and model(s) pnl
*/
type GetIserverAccountPnlPartitionedOK struct {
	Payload *GetIserverAccountPnlPartitionedOKBody
}

func (o *GetIserverAccountPnlPartitionedOK) Error() string {
	return fmt.Sprintf("[GET /iserver/account/pnl/partitioned][%d] getIserverAccountPnlPartitionedOK  %+v", 200, o.Payload)
}

func (o *GetIserverAccountPnlPartitionedOK) GetPayload() *GetIserverAccountPnlPartitionedOKBody {
	return o.Payload
}

func (o *GetIserverAccountPnlPartitionedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetIserverAccountPnlPartitionedOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetIserverAccountPnlPartitionedOKBody get iserver account pnl partitioned o k body
swagger:model GetIserverAccountPnlPartitionedOKBody
*/
type GetIserverAccountPnlPartitionedOKBody struct {

	// acct Id
	AcctID interface{} `json:"acctId,omitempty"`
}

// Validate validates this get iserver account pnl partitioned o k body
func (o *GetIserverAccountPnlPartitionedOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetIserverAccountPnlPartitionedOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetIserverAccountPnlPartitionedOKBody) UnmarshalBinary(b []byte) error {
	var res GetIserverAccountPnlPartitionedOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
