// Code generated by go-swagger; DO NOT EDIT.

package trades

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAccountTradesParams creates a new GetAccountTradesParams object
// with the default values initialized.
func NewGetAccountTradesParams() *GetAccountTradesParams {

	return &GetAccountTradesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAccountTradesParamsWithTimeout creates a new GetAccountTradesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAccountTradesParamsWithTimeout(timeout time.Duration) *GetAccountTradesParams {

	return &GetAccountTradesParams{

		timeout: timeout,
	}
}

// NewGetAccountTradesParamsWithContext creates a new GetAccountTradesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAccountTradesParamsWithContext(ctx context.Context) *GetAccountTradesParams {

	return &GetAccountTradesParams{

		Context: ctx,
	}
}

// NewGetAccountTradesParamsWithHTTPClient creates a new GetAccountTradesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAccountTradesParamsWithHTTPClient(client *http.Client) *GetAccountTradesParams {

	return &GetAccountTradesParams{
		HTTPClient: client,
	}
}

/*GetAccountTradesParams contains all the parameters to send to the API endpoint
for the get iserver account trades operation typically these are written to a http.Request
*/
type GetAccountTradesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get iserver account trades params
func (o *GetAccountTradesParams) WithTimeout(timeout time.Duration) *GetAccountTradesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get iserver account trades params
func (o *GetAccountTradesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get iserver account trades params
func (o *GetAccountTradesParams) WithContext(ctx context.Context) *GetAccountTradesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get iserver account trades params
func (o *GetAccountTradesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get iserver account trades params
func (o *GetAccountTradesParams) WithHTTPClient(client *http.Client) *GetAccountTradesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get iserver account trades params
func (o *GetAccountTradesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAccountTradesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
