// Code generated by go-swagger; DO NOT EDIT.

package trades

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "ibx/models"
)

// GetIserverAccountTradesReader is a Reader for the GetIserverAccountTrades structure.
type GetIserverAccountTradesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIserverAccountTradesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetIserverAccountTradesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetIserverAccountTradesOK creates a GetIserverAccountTradesOK with default headers values
func NewGetIserverAccountTradesOK() *GetIserverAccountTradesOK {
	return &GetIserverAccountTradesOK{}
}

/*GetIserverAccountTradesOK handles this case with default header values.

An array of trades
*/
type GetIserverAccountTradesOK struct {
	Payload []*models.Trade
}

func (o *GetIserverAccountTradesOK) Error() string {
	return fmt.Sprintf("[GET /iserver/account/trades][%d] getIserverAccountTradesOK  %+v", 200, o.Payload)
}

func (o *GetIserverAccountTradesOK) GetPayload() []*models.Trade {
	return o.Payload
}

func (o *GetIserverAccountTradesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
