// Code generated by go-swagger; DO NOT EDIT.

package trades

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetIserverAccountTradesParams creates a new GetIserverAccountTradesParams object
// with the default values initialized.
func NewGetIserverAccountTradesParams() *GetIserverAccountTradesParams {

	return &GetIserverAccountTradesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetIserverAccountTradesParamsWithTimeout creates a new GetIserverAccountTradesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetIserverAccountTradesParamsWithTimeout(timeout time.Duration) *GetIserverAccountTradesParams {

	return &GetIserverAccountTradesParams{

		timeout: timeout,
	}
}

// NewGetIserverAccountTradesParamsWithContext creates a new GetIserverAccountTradesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetIserverAccountTradesParamsWithContext(ctx context.Context) *GetIserverAccountTradesParams {

	return &GetIserverAccountTradesParams{

		Context: ctx,
	}
}

// NewGetIserverAccountTradesParamsWithHTTPClient creates a new GetIserverAccountTradesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetIserverAccountTradesParamsWithHTTPClient(client *http.Client) *GetIserverAccountTradesParams {

	return &GetIserverAccountTradesParams{
		HTTPClient: client,
	}
}

/*GetIserverAccountTradesParams contains all the parameters to send to the API endpoint
for the get iserver account trades operation typically these are written to a http.Request
*/
type GetIserverAccountTradesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get iserver account trades params
func (o *GetIserverAccountTradesParams) WithTimeout(timeout time.Duration) *GetIserverAccountTradesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get iserver account trades params
func (o *GetIserverAccountTradesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get iserver account trades params
func (o *GetIserverAccountTradesParams) WithContext(ctx context.Context) *GetIserverAccountTradesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get iserver account trades params
func (o *GetIserverAccountTradesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get iserver account trades params
func (o *GetIserverAccountTradesParams) WithHTTPClient(client *http.Client) *GetIserverAccountTradesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get iserver account trades params
func (o *GetIserverAccountTradesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetIserverAccountTradesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
