// Code generated by go-swagger; DO NOT EDIT.

package scanner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "ibx/models"
)

// NewPostScannerRunParams creates a new PostScannerRunParams object
// with the default values initialized.
func NewPostScannerRunParams() *PostScannerRunParams {
	var ()
	return &PostScannerRunParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostScannerRunParamsWithTimeout creates a new PostScannerRunParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostScannerRunParamsWithTimeout(timeout time.Duration) *PostScannerRunParams {
	var ()
	return &PostScannerRunParams{

		timeout: timeout,
	}
}

// NewPostScannerRunParamsWithContext creates a new PostScannerRunParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostScannerRunParamsWithContext(ctx context.Context) *PostScannerRunParams {
	var ()
	return &PostScannerRunParams{

		Context: ctx,
	}
}

// NewPostScannerRunParamsWithHTTPClient creates a new PostScannerRunParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostScannerRunParamsWithHTTPClient(client *http.Client) *PostScannerRunParams {
	var ()
	return &PostScannerRunParams{
		HTTPClient: client,
	}
}

/*PostScannerRunParams contains all the parameters to send to the API endpoint
for the post iserver scanner run operation typically these are written to a http.Request
*/
type PostScannerRunParams struct {

	/*Body
	  modify-order request

	*/
	Body *models.ScannerParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post iserver scanner run params
func (o *PostScannerRunParams) WithTimeout(timeout time.Duration) *PostScannerRunParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post iserver scanner run params
func (o *PostScannerRunParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post iserver scanner run params
func (o *PostScannerRunParams) WithContext(ctx context.Context) *PostScannerRunParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post iserver scanner run params
func (o *PostScannerRunParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post iserver scanner run params
func (o *PostScannerRunParams) WithHTTPClient(client *http.Client) *PostScannerRunParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post iserver scanner run params
func (o *PostScannerRunParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post iserver scanner run params
func (o *PostScannerRunParams) WithBody(body *models.ScannerParams) *PostScannerRunParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post iserver scanner run params
func (o *PostScannerRunParams) SetBody(body *models.ScannerParams) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostScannerRunParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
