// Code generated by go-swagger; DO NOT EDIT.

package scanner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// PostIserverScannerRunReader is a Reader for the PostIserverScannerRun structure.
type PostIserverScannerRunReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostIserverScannerRunReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostIserverScannerRunOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostIserverScannerRunOK creates a PostIserverScannerRunOK with default headers values
func NewPostIserverScannerRunOK() *PostIserverScannerRunOK {
	return &PostIserverScannerRunOK{}
}

/*PostIserverScannerRunOK handles this case with default header values.

returns an array
*/
type PostIserverScannerRunOK struct {
	Payload []*PostIserverScannerRunOKBodyItems0
}

func (o *PostIserverScannerRunOK) Error() string {
	return fmt.Sprintf("[POST /iserver/scanner/run][%d] postIserverScannerRunOK  %+v", 200, o.Payload)
}

func (o *PostIserverScannerRunOK) GetPayload() []*PostIserverScannerRunOKBodyItems0 {
	return o.Payload
}

func (o *PostIserverScannerRunOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostIserverScannerRunOKBodyItems0 post iserver scanner run o k body items0
swagger:model PostIserverScannerRunOKBodyItems0
*/
type PostIserverScannerRunOKBodyItems0 struct {

	// available chart periods
	AvailableChartPeriods string `json:"available_chart_periods,omitempty"`

	// column name
	ColumnName string `json:"column_name,omitempty"`

	// company name
	CompanyName string `json:"company_name,omitempty"`

	// con id
	ConID float64 `json:"con_id,omitempty"`

	// conidex
	Conidex string `json:"conidex,omitempty"`

	// contract description 1
	ContractDescription1 string `json:"contract_description_1,omitempty"`

	// listing exchange
	ListingExchange string `json:"listing_exchange,omitempty"`

	// sec type
	SecType string `json:"sec_type,omitempty"`

	// server id
	ServerID string `json:"server_id,omitempty"`

	// symbol
	Symbol string `json:"symbol,omitempty"`
}

// Validate validates this post iserver scanner run o k body items0
func (o *PostIserverScannerRunOKBodyItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostIserverScannerRunOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostIserverScannerRunOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res PostIserverScannerRunOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
