// Code generated by go-swagger; DO NOT EDIT.

package market_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "ibx/models"
)

// GetIserverMarketdataHistoryReader is a Reader for the GetIserverMarketdataHistory structure.
type GetIserverMarketdataHistoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIserverMarketdataHistoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetIserverMarketdataHistoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetIserverMarketdataHistoryOK creates a GetIserverMarketdataHistoryOK with default headers values
func NewGetIserverMarketdataHistoryOK() *GetIserverMarketdataHistoryOK {
	return &GetIserverMarketdataHistoryOK{}
}

/*GetIserverMarketdataHistoryOK handles this case with default header values.

Returns an object
*/
type GetIserverMarketdataHistoryOK struct {
	Payload *models.HistoryData
}

func (o *GetIserverMarketdataHistoryOK) Error() string {
	return fmt.Sprintf("[GET /iserver/marketdata/history][%d] getIserverMarketdataHistoryOK  %+v", 200, o.Payload)
}

func (o *GetIserverMarketdataHistoryOK) GetPayload() *models.HistoryData {
	return o.Payload
}

func (o *GetIserverMarketdataHistoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HistoryData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
