// Code generated by go-swagger; DO NOT EDIT.

package market_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMarketdataHistoryParams creates a new GetMarketdataHistoryParams object
// with the default values initialized.
func NewGetMarketdataHistoryParams() *GetMarketdataHistoryParams {
	var ()
	return &GetMarketdataHistoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMarketdataHistoryParamsWithTimeout creates a new GetMarketdataHistoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMarketdataHistoryParamsWithTimeout(timeout time.Duration) *GetMarketdataHistoryParams {
	var ()
	return &GetMarketdataHistoryParams{

		timeout: timeout,
	}
}

// NewGetMarketdataHistoryParamsWithContext creates a new GetMarketdataHistoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMarketdataHistoryParamsWithContext(ctx context.Context) *GetMarketdataHistoryParams {
	var ()
	return &GetMarketdataHistoryParams{

		Context: ctx,
	}
}

// NewGetMarketdataHistoryParamsWithHTTPClient creates a new GetMarketdataHistoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMarketdataHistoryParamsWithHTTPClient(client *http.Client) *GetMarketdataHistoryParams {
	var ()
	return &GetMarketdataHistoryParams{
		HTTPClient: client,
	}
}

/*GetMarketdataHistoryParams contains all the parameters to send to the API endpoint
for the get iserver marketdata history operation typically these are written to a http.Request
*/
type GetMarketdataHistoryParams struct {

	/*Bar
	  possible value-- 5min,1h,1w

	*/
	Bar *string
	/*Conid
	  contract id

	*/
	Conid string
	/*Period
	  time period-- 1d,1w,1m,1y

	*/
	Period string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get iserver marketdata history params
func (o *GetMarketdataHistoryParams) WithTimeout(timeout time.Duration) *GetMarketdataHistoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get iserver marketdata history params
func (o *GetMarketdataHistoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get iserver marketdata history params
func (o *GetMarketdataHistoryParams) WithContext(ctx context.Context) *GetMarketdataHistoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get iserver marketdata history params
func (o *GetMarketdataHistoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get iserver marketdata history params
func (o *GetMarketdataHistoryParams) WithHTTPClient(client *http.Client) *GetMarketdataHistoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get iserver marketdata history params
func (o *GetMarketdataHistoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBar adds the bar to the get iserver marketdata history params
func (o *GetMarketdataHistoryParams) WithBar(bar *string) *GetMarketdataHistoryParams {
	o.SetBar(bar)
	return o
}

// SetBar adds the bar to the get iserver marketdata history params
func (o *GetMarketdataHistoryParams) SetBar(bar *string) {
	o.Bar = bar
}

// WithConid adds the conid to the get iserver marketdata history params
func (o *GetMarketdataHistoryParams) WithConid(conid string) *GetMarketdataHistoryParams {
	o.SetConid(conid)
	return o
}

// SetConid adds the conid to the get iserver marketdata history params
func (o *GetMarketdataHistoryParams) SetConid(conid string) {
	o.Conid = conid
}

// WithPeriod adds the period to the get iserver marketdata history params
func (o *GetMarketdataHistoryParams) WithPeriod(period string) *GetMarketdataHistoryParams {
	o.SetPeriod(period)
	return o
}

// SetPeriod adds the period to the get iserver marketdata history params
func (o *GetMarketdataHistoryParams) SetPeriod(period string) {
	o.Period = period
}

// WriteToRequest writes these params to a swagger request
func (o *GetMarketdataHistoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Bar != nil {

		// query param bar
		var qrBar string
		if o.Bar != nil {
			qrBar = *o.Bar
		}
		qBar := qrBar
		if qBar != "" {
			if err := r.SetQueryParam("bar", qBar); err != nil {
				return err
			}
		}

	}

	// query param conid
	qrConid := o.Conid
	qConid := qrConid
	if qConid != "" {
		if err := r.SetQueryParam("conid", qConid); err != nil {
			return err
		}
	}

	// query param period
	qrPeriod := o.Period
	qPeriod := qrPeriod
	if qPeriod != "" {
		if err := r.SetQueryParam("period", qPeriod); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
