// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// GetSsoValidateReader is a Reader for the GetSsoValidate structure.
type GetSsoValidateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSsoValidateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSsoValidateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetSsoValidateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetSsoValidateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSsoValidateOK creates a GetSsoValidateOK with default headers values
func NewGetSsoValidateOK() *GetSsoValidateOK {
	return &GetSsoValidateOK{}
}

/*GetSsoValidateOK handles this case with default header values.

An Object
*/
type GetSsoValidateOK struct {
	Payload *GetSsoValidateOKBody
}

func (o *GetSsoValidateOK) Error() string {
	return fmt.Sprintf("[GET /sso/validate][%d] getSsoValidateOK  %+v", 200, o.Payload)
}

func (o *GetSsoValidateOK) GetPayload() *GetSsoValidateOKBody {
	return o.Payload
}

func (o *GetSsoValidateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetSsoValidateOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSsoValidateUnauthorized creates a GetSsoValidateUnauthorized with default headers values
func NewGetSsoValidateUnauthorized() *GetSsoValidateUnauthorized {
	return &GetSsoValidateUnauthorized{}
}

/*GetSsoValidateUnauthorized handles this case with default header values.

Authentication failed
*/
type GetSsoValidateUnauthorized struct {
}

func (o *GetSsoValidateUnauthorized) Error() string {
	return fmt.Sprintf("[GET /sso/validate][%d] getSsoValidateUnauthorized ", 401)
}

func (o *GetSsoValidateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetSsoValidateInternalServerError creates a GetSsoValidateInternalServerError with default headers values
func NewGetSsoValidateInternalServerError() *GetSsoValidateInternalServerError {
	return &GetSsoValidateInternalServerError{}
}

/*GetSsoValidateInternalServerError handles this case with default header values.

System failed
*/
type GetSsoValidateInternalServerError struct {
}

func (o *GetSsoValidateInternalServerError) Error() string {
	return fmt.Sprintf("[GET /sso/validate][%d] getSsoValidateInternalServerError ", 500)
}

func (o *GetSsoValidateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*GetSsoValidateOKBody get sso validate o k body
swagger:model GetSsoValidateOKBody
*/
type GetSsoValidateOKBody struct {

	// Time of session validation
	AUTHTIME float64 `json:"AUTH_TIME,omitempty"`

	// 1 for Live, 2 for Paper
	LoGINTYPE float64 `json:"LoGIN_TYPE,omitempty"`

	// true if session was validated; false if not.
	RESULT bool `json:"RESULT,omitempty"`

	// User ID
	USERID float64 `json:"USER_ID,omitempty"`

	// Username
	USERNAME string `json:"USER_NAME,omitempty"`

	// Time in milliseconds until session expires. Caller needs to call the again to re-validate session
	Expire float64 `json:"expire,omitempty"`
}

// Validate validates this get sso validate o k body
func (o *GetSsoValidateOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetSsoValidateOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetSsoValidateOKBody) UnmarshalBinary(b []byte) error {
	var res GetSsoValidateOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
