// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostIserverAuthStatusParams creates a new PostIserverAuthStatusParams object
// with the default values initialized.
func NewPostIserverAuthStatusParams() *PostIserverAuthStatusParams {

	return &PostIserverAuthStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostIserverAuthStatusParamsWithTimeout creates a new PostIserverAuthStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostIserverAuthStatusParamsWithTimeout(timeout time.Duration) *PostIserverAuthStatusParams {

	return &PostIserverAuthStatusParams{

		timeout: timeout,
	}
}

// NewPostIserverAuthStatusParamsWithContext creates a new PostIserverAuthStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostIserverAuthStatusParamsWithContext(ctx context.Context) *PostIserverAuthStatusParams {

	return &PostIserverAuthStatusParams{

		Context: ctx,
	}
}

// NewPostIserverAuthStatusParamsWithHTTPClient creates a new PostIserverAuthStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostIserverAuthStatusParamsWithHTTPClient(client *http.Client) *PostIserverAuthStatusParams {

	return &PostIserverAuthStatusParams{
		HTTPClient: client,
	}
}

/*PostIserverAuthStatusParams contains all the parameters to send to the API endpoint
for the post iserver auth status operation typically these are written to a http.Request
*/
type PostIserverAuthStatusParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post iserver auth status params
func (o *PostIserverAuthStatusParams) WithTimeout(timeout time.Duration) *PostIserverAuthStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post iserver auth status params
func (o *PostIserverAuthStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post iserver auth status params
func (o *PostIserverAuthStatusParams) WithContext(ctx context.Context) *PostIserverAuthStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post iserver auth status params
func (o *PostIserverAuthStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post iserver auth status params
func (o *PostIserverAuthStatusParams) WithHTTPClient(client *http.Client) *PostIserverAuthStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post iserver auth status params
func (o *PostIserverAuthStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostIserverAuthStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
