// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "learn2/models"
)

// PostIserverAuthStatusReader is a Reader for the PostIserverAuthStatus structure.
type PostIserverAuthStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostIserverAuthStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostIserverAuthStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostIserverAuthStatusOK creates a PostIserverAuthStatusOK with default headers values
func NewPostIserverAuthStatusOK() *PostIserverAuthStatusOK {
	return &PostIserverAuthStatusOK{}
}

/*PostIserverAuthStatusOK handles this case with default header values.

Authentication Status
*/
type PostIserverAuthStatusOK struct {
	Payload *models.AuthStatus
}

func (o *PostIserverAuthStatusOK) Error() string {
	return fmt.Sprintf("[POST /iserver/auth/status][%d] postIserverAuthStatusOK  %+v", 200, o.Payload)
}

func (o *PostIserverAuthStatusOK) GetPayload() *models.AuthStatus {
	return o.Payload
}

func (o *PostIserverAuthStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
