// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// PostLogoutReader is a Reader for the PostLogout structure.
type PostLogoutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostLogoutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostLogoutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostLogoutOK creates a PostLogoutOK with default headers values
func NewPostLogoutOK() *PostLogoutOK {
	return &PostLogoutOK{}
}

/*PostLogoutOK handles this case with default header values.

returned status indicates if user is logged in
*/
type PostLogoutOK struct {
	Payload *PostLogoutOKBody
}

func (o *PostLogoutOK) Error() string {
	return fmt.Sprintf("[POST /logout][%d] postLogoutOK  %+v", 200, o.Payload)
}

func (o *PostLogoutOK) GetPayload() *PostLogoutOKBody {
	return o.Payload
}

func (o *PostLogoutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostLogoutOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostLogoutOKBody post logout o k body
swagger:model PostLogoutOKBody
*/
type PostLogoutOKBody struct {

	// true means username is still logged in, false means it is not
	Confirmed bool `json:"confirmed,omitempty"`
}

// Validate validates this post logout o k body
func (o *PostLogoutOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostLogoutOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostLogoutOKBody) UnmarshalBinary(b []byte) error {
	var res PostLogoutOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
