// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostIserverReauthenticateParams creates a new PostIserverReauthenticateParams object
// with the default values initialized.
func NewPostIserverReauthenticateParams() *PostIserverReauthenticateParams {

	return &PostIserverReauthenticateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostIserverReauthenticateParamsWithTimeout creates a new PostIserverReauthenticateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostIserverReauthenticateParamsWithTimeout(timeout time.Duration) *PostIserverReauthenticateParams {

	return &PostIserverReauthenticateParams{

		timeout: timeout,
	}
}

// NewPostIserverReauthenticateParamsWithContext creates a new PostIserverReauthenticateParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostIserverReauthenticateParamsWithContext(ctx context.Context) *PostIserverReauthenticateParams {

	return &PostIserverReauthenticateParams{

		Context: ctx,
	}
}

// NewPostIserverReauthenticateParamsWithHTTPClient creates a new PostIserverReauthenticateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostIserverReauthenticateParamsWithHTTPClient(client *http.Client) *PostIserverReauthenticateParams {

	return &PostIserverReauthenticateParams{
		HTTPClient: client,
	}
}

/*PostIserverReauthenticateParams contains all the parameters to send to the API endpoint
for the post iserver reauthenticate operation typically these are written to a http.Request
*/
type PostIserverReauthenticateParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post iserver reauthenticate params
func (o *PostIserverReauthenticateParams) WithTimeout(timeout time.Duration) *PostIserverReauthenticateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post iserver reauthenticate params
func (o *PostIserverReauthenticateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post iserver reauthenticate params
func (o *PostIserverReauthenticateParams) WithContext(ctx context.Context) *PostIserverReauthenticateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post iserver reauthenticate params
func (o *PostIserverReauthenticateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post iserver reauthenticate params
func (o *PostIserverReauthenticateParams) WithHTTPClient(client *http.Client) *PostIserverReauthenticateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post iserver reauthenticate params
func (o *PostIserverReauthenticateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostIserverReauthenticateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
