// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostReauthenticateParams creates a new PostReauthenticateParams object
// with the default values initialized.
func NewPostReauthenticateParams() *PostReauthenticateParams {

	return &PostReauthenticateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostReauthenticateParamsWithTimeout creates a new PostReauthenticateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostReauthenticateParamsWithTimeout(timeout time.Duration) *PostReauthenticateParams {

	return &PostReauthenticateParams{

		timeout: timeout,
	}
}

// NewPostReauthenticateParamsWithContext creates a new PostReauthenticateParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostReauthenticateParamsWithContext(ctx context.Context) *PostReauthenticateParams {

	return &PostReauthenticateParams{

		Context: ctx,
	}
}

// NewPostReauthenticateParamsWithHTTPClient creates a new PostReauthenticateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostReauthenticateParamsWithHTTPClient(client *http.Client) *PostReauthenticateParams {

	return &PostReauthenticateParams{
		HTTPClient: client,
	}
}

/*PostReauthenticateParams contains all the parameters to send to the API endpoint
for the post iserver reauthenticate operation typically these are written to a http.Request
*/
type PostReauthenticateParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post iserver reauthenticate params
func (o *PostReauthenticateParams) WithTimeout(timeout time.Duration) *PostReauthenticateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post iserver reauthenticate params
func (o *PostReauthenticateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post iserver reauthenticate params
func (o *PostReauthenticateParams) WithContext(ctx context.Context) *PostReauthenticateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post iserver reauthenticate params
func (o *PostReauthenticateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post iserver reauthenticate params
func (o *PostReauthenticateParams) WithHTTPClient(client *http.Client) *PostReauthenticateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post iserver reauthenticate params
func (o *PostReauthenticateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostReauthenticateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
