// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Futures futures
// swagger:model futures
type Futures []*FuturesItems0

// Validate validates this futures
func (m Futures) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {
		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {
			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// FuturesItems0 future contract information
// swagger:model FuturesItems0
type FuturesItems0 struct {

	// conid of the future contract
	Conid int64 `json:"conid,omitempty"`

	// expiration date
	ExpirationDate string `json:"expirationDate,omitempty"`

	// last trading day
	Ltd string `json:"ltd,omitempty"`

	// symbol
	Symbol string `json:"symbol,omitempty"`

	// underlying conid
	UnderlyingConid int64 `json:"underlyingConid,omitempty"`
}

// Validate validates this futures items0
func (m *FuturesItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FuturesItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FuturesItems0) UnmarshalBinary(b []byte) error {
	var res FuturesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
