// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MarketData market data
// swagger:model market-data
type MarketData struct {

	// ask
	Ask float64 `json:"Ask,omitempty"`

	// ask size
	AskSize float64 `json:"AskSize,omitempty"`

	// bid
	Bid float64 `json:"Bid,omitempty"`

	// bid size
	BidSize float64 `json:"BidSize,omitempty"`

	// IBKR Contract ID
	Conid float64 `json:"Conid,omitempty"`

	// Exchange
	Exchange string `json:"Exchange,omitempty"`

	// last
	Last float64 `json:"Last,omitempty"`

	// last size
	LastSize float64 `json:"LastSize,omitempty"`

	// min tick
	MinTick float64 `json:"minTick,omitempty"`
}

// Validate validates this market data
func (m *MarketData) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MarketData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MarketData) UnmarshalBinary(b []byte) error {
	var res MarketData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
