// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ModifyOrder modify order
// swagger:model modify-order
type ModifyOrder struct {

	// acct Id
	AcctID string `json:"acctId,omitempty"`

	// aux price
	AuxPrice float64 `json:"auxPrice,omitempty"`

	// conid
	Conid int64 `json:"conid,omitempty"`

	// optional, not required
	ListingExchange string `json:"listingExchange,omitempty"`

	// customer orderid
	OrderID int64 `json:"orderId,omitempty"`

	// for example LMT
	OrderType string `json:"orderType,omitempty"`

	// outside r t h
	OutsideRTH bool `json:"outsideRTH,omitempty"`

	// price
	Price float64 `json:"price,omitempty"`

	// usually integer, for some special cases can be float numbers
	Quantity float64 `json:"quantity,omitempty"`

	// SELL or BUY
	Side string `json:"side,omitempty"`

	// ticker
	Ticker string `json:"ticker,omitempty"`

	// for example DAY
	Tif string `json:"tif,omitempty"`
}

// Validate validates this modify order
func (m *ModifyOrder) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModifyOrder) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModifyOrder) UnmarshalBinary(b []byte) error {
	var res ModifyOrder
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
