// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// StatsData stats data
// swagger:model stats-data
type StatsData struct {

	// conid
	Conid float64 `json:"Conid,omitempty"`

	// exchange
	Exchange string `json:"Exchange,omitempty"`

	// Object, payload depends on event type. See confluence page for IGEvntUpd.
	P string `json:"P,omitempty"`

	// t
	T float64 `json:"T,omitempty"`

	// t t
	TT float64 `json:"TT,omitempty"`

	// v
	V float64 `json:"V,omitempty"`
}

// Validate validates this stats data
func (m *StatsData) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StatsData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StatsData) UnmarshalBinary(b []byte) error {
	var res StatsData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
